### PR TITLE
DS81S20 temperature readings below zero fix

### PR DESCRIPTION
**Pull request by flexiti**
DS18S20 temperature readings below zero path

### CODE REVIEW

**Comment by hreintke** [comment]
Close & reopen to trigger travis rebuild

**Comment by flexiti** [comment]
@hreintke 
should be also improved in version RTOS

**Comment by hreintke** [comment]
@flexiti : 
Yes, This should also be included in Sming_RTOS.
Could make a PR that for that too ?

**Comment by flexiti** [comment]
ok

**Pull request merged**
