### PR TITLE
Install library python prerequisites by default.

### PR DESCRIPTION
**Pull request by slaff**

### CODE REVIEW

**Comment by mikee47** [comment]
There was discussion previously about mixing installation stuff up with a build. In particular, it would break any custom python installation the user might choose. See https://github.com/SmingHub/Sming/pull/2019#issuecomment-574377010

**Comment by mikee47** [comment]
What we could do is ensure that modules aren't imported until they're actually used - that would avoid issues with `make help`, etc.

**Comment by slaff** [comment]
>  it would break any custom python installation the user might choose

We can make things get more complicated and use `virtualenv` which will contain only the packages for Sming. But from my experience people get confused pretty quickly...

> Already done that!

What do you mean here?

**Comment by mikee47** [comment]
The argument here (which I tend to agree with) is the separation of installation and building steps. Having stuff installed 'in the background' is not appropriate.

By 'already done that' I meant moving the module import into the code itself, but the error in question (missing `rjsmin`) is with code which already does that. Removing rjsmin entirely would be one solution but my feeling is that supporting comments makes dealing with JSON more user-friendly, and it's the simplest approach I can think of.

Having said all this there is clearly still an issue because on a fresh clone running `make python-requirements` won't work! I'll get a fix sorted out for that.

**Comment by mikee47** [comment]
This works:

```
make -C $SMING_HOME python-requirements
```

But again it should be done as part of the Sming installation. #2240 should help a bit with this .

**Comment by mikee47** [comment]
I'm thinking with `rjsmin` it should be baked-in rather than an installed package. Easy enough to do and should avoid this problem entirely.

**Comment by slaff** [comment]
Superseded by PR #2223.

**Pull request closed without merging**
