### PR TITLE
Revise TWI to support ESP32

### PR DESCRIPTION
**Pull request by mikee47**
Simplest solution for this is to retain existing sofware TWI code. Using the hardware is more complex and really only justifiable if asynchronous operation required, which would require a different interface.

TODO:

* [x] Verify SDA/SCL output timing on scope
* [x] Test with real I2C device.

```
SCL timings in kHz (approx.)

@80MHz
Count  ESP8266  ESP32
16      99      104
5      200      221
2      276      319
0      371      454

@160MHz
Count  ESP8266  ESP32  240MHz
28     102       66     66
12     191      129    129
5      310      221    221
3      377      278    278
1      479      374    375
0      559      455    455
```

Note: Timings likely to vary more significantly if ESP32 APB freq. changes

### CODE REVIEW

**Comment by slaff** [comment]
@mikee47 PR #2188 is now merged. You can rebase on latest `develop` and check with real I2C device.

**Comment by mikee47** [comment]
Tested with DS3232RTC_NTP_Setter sample application, some fixes required for ESP32 (#2191)

**Comment by slaff** [comment]
@mikee47 PR #2191 is merged. You can rebase and retest if needed.

**Comment by mikee47** [comment]
@slaff OK rebased, re-tested on both ESP8266 and ESP32

**Pull request merged**
