### PR TITLE
Stream optimisations

### PR DESCRIPTION
**Pull request by mikee47**
-   Simplify Multipart streams
    
    -   Remove `nextStream` and make `stream` private.
    -   Remove `onNextStream` method and implement logic within MultipartStream::getNextStream.
    -   Deprecate `HttpPartResult`, rename as `MultipartStream::BodyPart`.
    -   Deprecate `HttpPartProducerDelegate`, rename as `MultipartStream::Producer`.

-   Wiring Stream
    -   Apply coding style to `Stream.h` and regularise comments
    -   Move trivial Stream methods into header
    -   Apply coding style, simplify and tidy up Stream.cpp
    -   Also add a couple of extra null ptr checks
    -   Stream find methods should take `const char*`

-   Fix LimitedMemoryStream, and add `getStreamPointer` method
    
    -   Attempting to write data larger than available space discards all of it.
    -   Correct behaviour is to write as much as possible, but still discard the remainder.
    -   Make seek operation (for reading) is bi-directional between the start of the buffer and the current write position.

-   Add serialization speed checks in HostTests

### CODE REVIEW

**Comment by mikee47** [comment]
HostTests has added speed tests using Json6. Here's a summary of the changes running on a NodeMCU.

Times are in microseconds:

- loadBuffer

| Before | After |
|--------|-------|
| 1059   | 1063  |
| 868    | 868   |
| 860    | 868   |
| 860    | 868   |

- loadFlashString

| Before | After |
|--------|-------|
| 2386 | 2342
| 2267 | 2240
| 2267 | 2236
| 2267 | 2236

- loadFlashString via Stream (cached)

| Before | After |
|--------|-------|
| 3665 | 3656 |
| 3444 | 3439 |
| 3444 | 3440 |
| 3444 | 3440 |

- loadFlashString via Stream (un-cached)

| Before | After |
|--------|-------|
| 9238 | 9242 |
| 9203 | 9187 |
| 9207 | 9191 |
| 9203 | 9187 |

- loadFile

| Before | After |
|--------|-------|
| 4877 | 4621 |
| 4306 | 4068 |
| 4263 | 4023 |
| 4263 | 4019 |

- loadStream

| Before | After |
|--------|-------|
| 4154 | 3903 |
| 4134 | 3872 |
| 4127 | 3872 |
| 4127 | 3872 |

**Comment by slaff** [comment]
@mikee47 Run `make -C $SMING_HOME cs`. The coding style check for the tests is failing:
```
--- a/tests/HostTests/app/test-json6.cpp
+++ b/tests/HostTests/app/test-json6.cpp
@@ -263,7 +263,7 @@ public:
 		TEST_CASE("Speed checks")
 		{
 			speedChecks();
-	}
+		}
 	}
 
 	void __attribute__((noinline)) loadBuffer(const char* buffer, size_t length)'
++'[' 'diff --git a/tests/HostTests/app/test-json6.cpp b/tests/HostTests/app/test-json6.cpp
index c78f620..291c446 100644
--- a/tests/HostTests/app/test-json6.cpp
+++ b/tests/HostTests/app/test-json6.cpp
@@ -263,7 +263,7 @@ public:
 		TEST_CASE("Speed checks")
 		{
 			speedChecks();
-	}
+		}
 	}
 
 	void __attribute__((noinline)) loadBuffer(const char* buffer, size_t length)' '!=' '' ']'
++echo '!!! Coding Style issues Found!!!'
!!! Coding Style issues Found!!!
++echo '    Run: '\''make cs'\'' to fix them. '
    Run: 'make cs' to fix them. 
++echo 'diff --git a/tests/HostTests/app/test-json6.cpp b/tests/HostTests/app/test-json6.cpp
index c78f620..291c446 100644
--- a/tests/HostTests/app/test-json6.cpp
+++ b/tests/HostTests/app/test-json6.cpp
@@ -263,7 +263,7 @@ public:
 		TEST_CASE("Speed checks")
 		{
 			speedChecks();
-	}
+		}
 	}
 
 	void __attribute__((noinline)) loadBuffer(const char* buffer, size_t length)'
diff --git a/tests/HostTests/app/test-json6.cpp b/tests/HostTests/app/test-json6.cpp
index c78f620..291c446 100644
--- a/tests/HostTests/app/test-json6.cpp
+++ b/tests/HostTests/app/test-json6.cpp
@@ -263,7 +263,7 @@ public:
 		TEST_CASE("Speed checks")
 		{
 			speedChecks();
-	}
+		}
 	}
 
 	void __attribute__((noinline)) loadBuffer(const char* buffer, size_t length)
```

**Comment by slaff** [comment]
@mikee47 Is this PR ready for merging?

**Comment by mikee47** [comment]
@slaff Yes, all done

**Pull request merged**
