### PR TITLE
Changed WS2812 example: removed delay and WDT refresh

### PR DESCRIPTION
**Pull request by flexiti**
WS8212 example   it must be tested because I do not have WS2812
 Also added 2 new metods getRssi() and getChannel() in StationClass
(can read actual WiFi signal level and the channel number)

### CODE REVIEW

**Comment by flexiti** [comment]
Renaming function

**Comment by flexiti** [comment]
Can someone merge it? I think it's safe to change

**Comment by kireevco** [comment]
@flexiti can you please update PR description? What is it doing and what is the impact?
(We need this to be included in the changelog).

**Comment by flexiti** [comment]
@kireevco 
its ok  now ?  
There is also 2 new metods  getRssi() and getChannel() in StationClas but I do not know where to write info - in the same line as info about new example  versiona of WS2812 ?

**Comment by kireevco** [comment]
@flexiti I change the wording a little bit. Does that make sense?

you can write here:
>It can be done in this way, it must be tested because I do not have WS2812

**Comment by flexiti** [comment]
@kireevco 
its ok

**Comment by tprochazka** [comment]
Why this is still not merged?

**Comment by tprochazka** [comment]
I tried use it. Example works correctly, but when I use the library in real project where WifiStation is connected it doesn't work, it produce completely different color. I know that it is not problem of this PR, but I would ask if you tried it on the more complex application than example?

**Comment by alonewolfx2** [comment]
@tprochazka what is your not working code part? i am using in one project and its connected to wifi and its working fine

**Comment by anakod** [comment]
> I tried use it. Example works correctly, but when I use the library in real project where WifiStation is connected it doesn't work, it produce completely different color.

I think what may be we should try to add interrupts lock during color data transmission?

**Comment by alonewolfx2** [comment]
> I think what may be we should try to add interrupts lock during color data transmission?

right. i am using it. maybe i can push PR

**Comment by flexiti** [comment]
@kireevco 
Can You merge it to develop ?
Previous example was taken from the Arduino, without the necessary changes specific to sming and ESP, this one is good.
@tprochazka 
after the publication can check and then let me know?
I think that the example will run well, certainly there are any errors in another library - I can check it out but first we must have same version

**Comment by hreintke** [comment]
@flexiti : 
I see comments from @alonewolfx2 that additional PR would be needed and @tprochazka @anakod .
That there are issues when wifi is connected .

**Comment by flexiti** [comment]
@hreintke 
I think that You can publish it, because there is no error in this demo.
The fault is in the library es2812, function ws2812_writergb () (previous version of demo also have this fault)
I can improve this library in my free time. (I see that ws2812_writergb () not pay attention to the time of transmission !! - so important for ws2812)


To sum up, certainly this demo will not be worse than it is now, but better  ;)

**Comment by alonewolfx2** [comment]
i think we can delete this example and library. because adafruit library very powerfull.

**Comment by flexiti** [comment]
@alonewolfx2 
Your demo, you can delete the demo :) 
 Although copying everything from Arduino is not necessarily effective, maybe perhaps it our library is already so big.
@hreintke 
Please keep however, getRssi and getChannel.
(maybe the easiest way to publish it, and then remove the demo WS2812)

**Comment by hreintke** [comment]
@flexiti : @alonewolfx2 : 
I am lost in this discussion. No idea anymore which library/example is OK/not OK.
Please clarify.

@flexiti : Pulling something in, just to remove it afterwards is not a way to keep history clean.
Maybe should have said it before (as I did in other case lately) but now we the discussion above : 
Please split the PR in two. 1/ SmingCore update (Rssi) and 2/ Library and example.
In that way we keep the repo clean and updates understandable/traceable.

**Comment by flexiti** [comment]
@hreintke , please publish it, next @alonewolfx2 remove his example...It is the simplest and clean  solution and it will take a few seconds, otherwise I'll have to play the amendments and publish them again - a waste of time

**Comment by alonewolfx2** [comment]
@flexiti which example ? ws2812 example isnt mine. i ported just adafruit library and ported adafruit example.
@hreintke both examples working fine but just 2 library for ws2812 unnecessary. Adafruit_neopixel library ad example can stay and we can remove old ws2812 library for keep clean.

**Comment by flexiti** [comment]
colleagues, the only time we lose here :) Please @hreintke  publish it, and then @hreintke or @alonewolfx2 delete this example.
I have just been asked to improve this example, neopixel example  and OLED display example- What I did.
 I would also like to organize itself, my  develop... so please, no more comments please...just let do it :)

**Comment by flexiti** [comment]
@alonewolfx2 @hreintke 
Colleagues, can you? I'm already tired of asking to merge it

**Pull request closed without merging**
