### PR TITLE
MQTT LWT Fix : issue #491

### PR DESCRIPTION
**Pull request by etmmahi**
Fix for #491 
In MqttClient::connect() mqtt_init() cleared the LWT already set. 
Pull request changes order of initialization
In constructor the broker is cleared. Later in connect the clientid is overwritten when supplied.

### CODE REVIEW

**Comment by Informatic** [comment]
I can confirm it is working fine now.

**Comment by hreintke** [comment]
@etmmahi : 
- Will this also work when the application calls connect multiple times on an instance ? 
- Better to make mqtt_init(&broker, NULL) -> makes clear it is a pointer instead of a value.

**Comment by etmmahi** [comment]
Hi, thanks for testing an commenting.

I have updated the pull request with the NULL pointer. (Style update)

Furthermore the client can still reconnect with these changes on the same instance.
Even better, there was a memleak in the LWT implementation when a LWT was set for the connection. 
The LWT was allocated again for the new connection instance. (previous LWT was not freed). This is now also fixed.

**Comment by ashubhatt** [comment]
I have tested the code. It works.

**Comment by etmmahi** [comment]
Hi
@ashubhatt 
Where did your fix for "LWT will not work when used with MQTT username and password." go?

**Comment by ashubhatt** [comment]
Hey @etmmahi ,

Kindly find the fix at: https://github.com/ashubhatt/testSming/

**Comment by gschmottlach** [comment]
Looking at the  fix here: https://github.com/ashubhatt/testSming/

It doesn't look like "will retain" and "will QoS" parameters are being encoded into the flags parameter in the mqtt_connect() function.  I think something along the lines of the following should be added:

```
if(willtopiclen) {
	payload_len += willtopiclen + strlen(broker->will_message) + 4;
	flags |= MQTT_WILL_FLAG;

	if ( broker->will_retain ) {
		flags |= MQTT_WILL_RETAIN;
	}

	flags |= (((unsigned)broker->will_qos & 0x03) << 3)
}
```

Without setting the ```flags``` variable you can't set the retained or QoS options for the LWT.

**Comment by ashubhatt** [comment]
@gschmottlach Thanks for noticing that.

I forgot to look at the flags. The library is patched now.

**Comment by etmmahi** [comment]
@ashubhatt  I checked the two patches against MQTT Version 3.1.1 OASIS Standard
both are fine. Now get them merged in develop. So we can get the MQTT lib fully functional with LWT

**Comment by etmmahi** [comment]
@hreintke Can we get this one merged?  

@ashubhatt  can you create pull request to fix the order of the username and message in the connect()

To finalize there is also a PR/pull request needed for adding the correct flags in the connect message (see comment @gschmottlach)

Time to finish up the LWT issues

**Comment by etmmahi** [comment]
Closed due to merge of #565

**Pull request closed without merging**
