### PR TITLE
Fix rawbody being empty

### PR DESCRIPTION
**Pull request by patrickjahns**
I discovered that the rawbody data might be empty, if header and body are not in the same packet/lwip buffer. 

It is based on the buffer for header (PR #622)

### CODE REVIEW

**Comment by patrickjahns** [comment]
One remark - is it wise to return String with `getBody()` ? Would it save memory when we return a String pointer instead?

**Comment by hreintke** [comment]
This is the internal representation of String : 
```
  protected:
    char *buffer;	        // the actual char array
    uint16_t capacity;  // the array length minus one (for the '\0')
    uint16_t len;       // the String length (not counting the '\0')
```
S it does use pointer already. 
Other maybe to consider is that C/C++ people are used to working with char* when handling buffers. 
But String* doesn't seem necessary

**Comment by patrickjahns** [comment]
So essentially when returning String it is not duplicated? That`s why I wonder if it wouldn`t be better returning a pointer to the String instead? 

(sorry it`s been a while since I worked in c/c++ - usually work in python)

**Comment by patrickjahns** [comment]
I`ve synchronized this with the latest changes in buffering the http header.

**Comment by avr39-ripe** [comment]
Check this patch on top of today develop - WORKS for me! I can still get queryParameters, I can get rawBody so I'm VERY glad. Thank you for your contribution! It will be great if someone who had problem with split packets confirm this to work.

**Comment by hreintke** [comment]
@patrickjahns : 
I am a little lost in the discussions we had and the relationship between them.
Is this PR now ready to merge ?

**Comment by patrickjahns** [comment]
@hreintke 

The discussion was about if the Method `getBody();` should return a pointer to the String object or the object itself (memory wise)

Otherwise it is ready for merge

**Comment by avr39-ripe** [comment]
@hreintke is there something missing/undone to merge this PR? Thanks!

**Comment by alonewolfx2** [comment]
@hreintke any suggestions? I will merge it

**Comment by hreintke** [comment]
@patrickjahns @avr39-ripe @alonewolfx2 : 
Sorry, indeed has taken to long to react (have been busy last time).
And have been doubting about this. 
There is a copy when returning the String. however, it is not on the stack but on heap, and there is almost no usage of String* within Sming.
Let's keep it to String for now.

**Pull request merged**
