### PR TITLE
Update appveyor build to use latest MinGW

### PR DESCRIPTION
**Pull request by mikee47**
Let's have another try to get appveyor working again.
For reference, appveyor builds on my account are without issue.

### CODE REVIEW

**Comment by mikee47** [comment]
No effect. Closing as other issue is still open.

**Comment by slaff** [comment]
Appveyor is really bugging me. We should try [Travis Windows builds](https://docs.travis-ci.com/user/reference/windows/)

**Comment by mikee47** [comment]
@slaff On the plus (!) side, as of yesterday I'm working with this latest version of MinGW (which has GCC 9.2 vs 8.2) and.. guess what:

```
CC /s/sandboxes/sming-tmp/Sming/Components/bearssl-esp8266/bearssl/src/x509/skey_decoder.c
CC /s/sandboxes/sming-tmp/Sming/Components/bearssl-esp8266/bearssl/src/x509/x509_decoder.c
CC /s/sandboxes/sming-tmp/Sming/Components/bearssl-esp8266/bearssl/src/x509/x509_knownkey.c
CC /s/sandboxes/sming-tmp/Sming/Components/bearssl-esp8266/bearssl/src/x509/x509_minimal.c
CC /s/sandboxes/sming-tmp/Sming/Components/bearssl-esp8266/bearssl/src/x509/x509_minimal_full.c
AR /s/sandboxes/sming-tmp/Sming/out/Host/debug/lib/clib-bearssl-esp8266.a
C:\MinGW\msys\1.0\bin\make.exe: *** couldn't commit memory for cygwin heap, Win32 error 0
make: *** [bearssl-esp8266-build] Error 1
```

So finally, I can reproduce the error on my dev. machine. I've got 32GB RAM so it's not that :-)

**Comment by slaff** [comment]
> So finally, I can reproduce the error on my dev. machine.

Try to find the culprit but don't investigate too much time on this.

**Comment by mikee47** [comment]
@slaff Are you looking into `Windows on Travis` or shall I have a pop?

**Comment by mikee47** [comment]
@slaff Scratch my question I see you're cracking on :-)

**Comment by slaff** [comment]
> Are you looking into Windows on Travis or shall I have a pop?

But my progress is sooo slow  that I have nothing against you trying Windows on Travis.

**Comment by mikee47** [comment]
@slaff Made some (slow) progress with travis builds - https://travis-ci.org/github/mikee47/Sming/builds/738497211

Strangely, it's failed running some crypto tests - investigating - but progress!

**Pull request closed without merging**
