### PR TITLE
Added mcp23017

### PR DESCRIPTION
**Pull request by crosofg**
Added the Example and Library for MCP23017 I/O Port Expander.

### CODE REVIEW

**Comment by anakod** [comment]
Is it tested on hardware?

**Comment by crosofg** [comment]
yes. it is working.

**Comment by hreintke** [comment]
@crosofg : 
Can you submit a PR for SmingRTOS too ?

**Comment by alon24** [comment]
+1 for rtos

**Comment by alon24** [comment]
I just got these at the mail

**Comment by crosofg** [comment]
@hreintke made a PR against rtos master.

**Pull request merged**
