### PR TITLE
test PR

### PR DESCRIPTION
**Pull request by zhivko**

### CODE REVIEW

**Comment by alonewolfx2** [comment]
my drivers working fine ?

**Comment by kireevco** [comment]
(Just that we know) this can't be merged until squashed

**Comment by alonewolfx2** [comment]
> (Just that we know) this can't be merged until squashed

@kireevco is right.

**Comment by zhivko** [comment]
Sorry guys - I made mistake - wanted to merge from SmingHub:master to my repo master - and this was mistake.
Sorry again - can somebody delete this PR?

**Comment by alonewolfx2** [comment]
Closed.

**Comment by hreintke** [comment]
@zhivko Just FYI : 
- If something like this happens again, you are able to close all issues and PR's YOU submitted yourself. 

- PR's cannot be deleted only closed, so information on content is still reachable in Github.

**Pull request closed without merging**
