### PR TITLE
Split DataSourceStream contents into separate files

### PR DESCRIPTION
**Pull request by mikee47**
No code changes have been made, just rearranging content and tidying #includes.

Unexpected conflicts occurred with libmain (see below) because of module re-ordering. The simplest solution I could find was to put LIBSMING before LIBMAIN in the makefiles.

```
out/build/libmain2.a(time.o): In function `millis':
(.irom0.text+0xb4): undefined reference to `sntp_set_update_delay'
out/build/libmain2.a(time.o): In function `millis':
(.irom0.text+0xbd): undefined reference to `sntp_set_update_delay'
out/build/libmain2.a(time.o): In function `micros':
(.irom0.text+0xe0): undefined reference to `sntp_set_daylight'
out/build/libmain2.a(time.o): In function `micros':
(.irom0.text+0xe4): undefined reference to `sntp_set_timetype'
out/build/libmain2.a(time.o): In function `updateTime':
(.irom0.text+0xe8): undefined reference to `sntp_set_receive_time_size'
out/build/libmain2.a(time.o): In function `updateTime':
(.irom0.text+0x134): undefined reference to `sntp_set_daylight'
out/build/libmain2.a(time.o): In function `configTime':
(.irom0.text+0x13c): undefined reference to `sntp_set_timetype'
out/build/libmain2.a(time.o): In function `configTime':
(.irom0.text+0x169): undefined reference to `sntp_set_receive_time_size'
out/build/libmain2.a(time.o): In function `configTime':
(.irom0.text+0x1a8): undefined reference to `sntp_get_timetype'
out/build/libmain2.a(time.o): In function `configTime':
(.irom0.text+0x1bb): undefined reference to `sntp_get_timetype'
```

### CODE REVIEW

**Comment by slaff** [comment]
> Unexpected conflicts occurred with libmain (see below) because of module re-ordering

That is strange. Have to see what causes this issue.

**Comment by mikee47** [comment]
> > Unexpected conflicts occurred with libmain (see below) because of module re-ordering
> 
> That is strange. Have to see what causes this issue.

Code in libmain will be similar to https://github.com/SmingHub/Sming/pull/921/files#diff-d44fb43f803dd802f47ca98e426f664a from #921

**Comment by mikee47** [comment]
> > Unexpected conflicts occurred with libmain (see below) because of module re-ordering
> 
> That is strange. Have to see what causes this issue.

Do you need any more information about this? The makefile change does fix it, and it seems logical that definitions from SmingCore should override libmain anyway.

**Comment by slaff** [comment]
> The makefile change does fix it, and it seems logical that definitions from SmingCore should override libmain anyway.

I agree with you.

> Fixing the Codacy issues is minor, can do that in this PR If you want?

Yes, please.

**Comment by slaff** [comment]
>> Fixing the Codacy issues is minor, can do that in this PR If you want?

> Yes, please.

@mikee47 When you have time push the new changes and I will take care to merge the PR. I think that the codacy issues are the last things that needs to be done for this PR.

**Pull request merged**
