### PR TITLE
- initial ArduCAM library and sample replaces #646

### PR DESCRIPTION
**Pull request by harry-boe**
Basic implementation for the ArduCAM, 2MP type OV2640

Sample provides web page to capture JPG images from the camera using the browser. 
The image size can be set using a command handler at runtime by console or telnet

Note: PR replaces #646 to cleanup dependencies after merging #642

### CODE REVIEW

**Comment by hreintke** [comment]
@harry-boe : 
Clening issues/PR's
Is this still a valid PR or is it obsolete after you work afterwards ?

**Comment by alonewolfx2** [comment]
@hreintke its still valid :)

**Comment by harry-boe** [comment]
sorry for the late response ..

Yes the PR is still fine. It's based on the new SPI implementation and works fine for GIF image capturing for all supported sizes up to 2MP.
It comes with a nice web ui to capture and display the images.
We used that code already for a training workshop with +20 participants/devices ai it's well tested;)

BTW: The web page uses a css and javascript library that is optimised for size and does not need to load code from a CDN -> might be an option for other build in web sites as well.
Videos are not yet supported -> this would requires a InputStream that creates a multipart response basically adding picture by picture. 
I will add that once i have some time left.

Issues: The BMP mode deliver some strange results wit the picture up-side-down and some weird colours. Maybe a byte order issue - but anyhow JPG's are all fine.

**Comment by alonewolfx2** [comment]
is #642 still necessary?

**Comment by harry-boe** [comment]
#642 got merged already that was the new SPI implementation.

**Pull request merged**
