### PR TITLE
Added libcrypto needed to compile against sdk 1.5

### PR DESCRIPTION
**Pull request by ADiea**
Added libcrypto needed to compile against sdk 1.5
http://espressif.com/new-sdk-release/

### CODE REVIEW

**Comment by alonewolfx2** [comment]
@ADiea it need test for backward sdk compatibility.

**Comment by raburton** [comment]
@alonewolfx2 apps still compile fine against sdk v1.4.0

**Comment by ADiea** [comment]
compiled with 

esp_iot_sdk_v1.3.0_15_08_08 FAILS
\sming\sming\smingcore\platform\station.h:36:25: error: 'SC_TYPE_ESPTOUCH_AIRKISS' was not declared in this scope -> not related to crypto lib

esp_iot_sdk_v1.4.1_15_10_27 SUCCESS

esp_iot_sdk_v1.5.0_15_11_27 SUCCESS

**Comment by hreintke** [comment]
@ADiea : 
This is a know "issue".
We decided to not make Develop & next release backward compatible with SDK 1.3.0

**Pull request merged**
