### PR TITLE
Fix Makefile targets

### PR DESCRIPTION
**Pull request by ADiea**
When setting more patchs for include dirs and/or for module targets the operator ?= will not work anymore.+= is needed, and is also backwards compatible to the case when the custom application makefile does not set any values for MODULES and extra include dir.

### CODE REVIEW

**Comment by hreintke** [comment]
@raburton : @kireevco : 
Can you comment on this PR and if OK, merge into develop ?

**Comment by kireevco** [comment]
older .travis.yml here, doesn't pull right sdk. @ADiea can you please get the latest so the test won't fail?

**Comment by ADiea** [comment]
Sure sorry old PR, didn't realise

**Comment by raburton** [comment]
Looks fine to me.

**Comment by raburton** [comment]
I think I'm going to have to reverse my opinion here. Why do we want to append to the modules list? If the user wants to set it that's fine, if they want to keep 'app' in the list they can add it to their own, that's the default in the Makefile-user.mk files shipped with the samples so they just need to add their own modules to the list. If they don't want 'app' at all, they define their own variable and we shouldnt; add app to it. Happy to keep the EXTRA_INCDIR, because we add a lot of stuff that we should, but I think better to separate the two so they can override the default project include directory (as they can for app), but always add the Sming stuff on too. I'll submit a new pr...

**Comment by ADiea** [comment]
You are right for the modules, should be reversed. Will you make a PR out of your latest commit or should I do it?
Thank you for noticing!

**Comment by raburton** [comment]
Done, see #507. Standardised all the sample makefile-user.mk files too (so you'll have to search the changes page to see the most important could of files).

**Pull request merged**
