### PR TITLE
Small changes allowing the use of C++11 std::function.

### PR DESCRIPTION
**Pull request by slaff**
Related to #1337.

### CODE REVIEW

**Comment by avr39-ripe** [comment]
@slaff I try this to convert my class from Delegates to std::function & std::bind and it works with minor modification:
in SmingCore.h we need add
#include <algorithm>
#define max(A, B) std::max(A, B)

and in Wconstants.h change max to 
#ifndef max
#define max(a,b)                       ((a)>(b)?(a):(b))
#endif

without this modification std::vector throws error on compilation. Tested on recompiled recent sming and recompiled and flashed app. Memory usage is liiitle bit greater than with plain old Delegate, but it works1 :) and open new world of std::bind and friends to Sming:)

**Comment by slaff** [comment]
> and it works with minor modification:
in SmingCore.h we need add
#include 
#define max(A, B) std::max(A, B)

> and in Wconstants.h change max to
#ifndef max
#define max(a,b) ((a)>(b)?(a):(b))
#endif

@avr39-ripe Well actually those changes are already part of the PR?! I didn't quite understood if I should change something there?

**Comment by avr39-ripe** [comment]
no, it isn't part of orig pr, you need add this

**Comment by slaff** [comment]
@avr39-ripe That is weird. I can see the following in the patch file (https://patch-diff.githubusercontent.com/raw/SmingHub/Sming/pull/1353.patch)

```
diff --git a/Sming/SmingCore/SmingCore.h b/Sming/SmingCore/SmingCore.h
index e44f7a510..fcb4fbca9 100644
--- a/Sming/SmingCore/SmingCore.h
+++ b/Sming/SmingCore/SmingCore.h
@@ -10,6 +10,10 @@
 
 #define SMING_VERSION "3.5.1" // Major Minor Sub
 
+#include <functional>
+
+#define min(A, B) std::min(A, B)
+
 #include "../Wiring/WiringFrameworkIncludes.h"
```

and further on...

```
--- a/Sming/Wiring/WConstants.h
+++ b/Sming/Wiring/WConstants.h
@@ -114,7 +114,9 @@
 
 #define sq(x)                          ((x)*(x))
 //#define abs(x)                         ((x)>0?(x):-(x))
+#ifndef min
 #define min(a,b)                       ((a)<(b)?(a):(b))
+#endif
 #define max(a,b)                       ((a)>(b)?(a):(b))
```

**Comment by avr39-ripe** [comment]
@slaff in pr there is M I N addition, and I talk about M A X addition.  by the way in SmingCore h we need#include <algorithm> for std::max
Do you see what I mean now? :)

**Comment by slaff** [comment]
> Do you see what I mean now? :)

@avr39-ripe I see I see, said the blind man :) Thanks for pointing this out.

**Comment by horde3d** [comment]
By the way, having the preprocessor macros min and max defined globally without namespace might cause problems in DateTime.cpp, as there are parameters/variables called min for minute that would be replaced by the preprocessor with nonsense, wouldn't it?

**Comment by slaff** [comment]
>  there are parameters/variables called min for minute that would be replaced by the preprocessor with nonsense, wouldn't it?

I don't think so. You can easily check this by calling the compiler with -E instead of -c.  You can use the command below:

```
cd $SMING_HOME
xtensa-lx106-elf-g++ -Isystem -Isystem/helpers -IWiring -Iappinit -ISmingCore/ -ISmingCore/Network/ -ISmingCore/Network/Http/ -ISmingCore/Network/Http/Stream/ -ISmingCore/Network/Http/Websocket/ -ISmingCore/Platform/ -IServices/ArduinoJson/ -IServices/CommandProcessing/ -IServices/cWebsocket/ -IServices/DateTime/ -IServices/FATFS/ -IServices/HexDump/ -IServices/libemqtt/ -IServices/SpifFS/ -IServices/WebHelpers/ -IServices/Yeelight/ -ILibraries/Adafruit_BME280_Library/ -ILibraries/Adafruit_GFX/ -ILibraries/Adafruit_ILI9341/ -ILibraries/Adafruit_NeoPixel/ -ILibraries/Adafruit_PCD8544/ -ILibraries/Adafruit_Sensor/ -ILibraries/Adafruit_SSD1306/ -ILibraries/Adafruit_ST7735/ -ILibraries/AM2321/ -ILibraries/APA102/ -ILibraries/ArduCAM/ -ILibraries/BH1750FVI/ -ILibraries/BMP180/ -ILibraries/Bounce/ -ILibraries/CapacitiveSensor/ -ILibraries/DHT/ -ILibraries/DS18S20/ -ILibraries/DS3232RTC/ -ILibraries/HMC5883L/ -ILibraries/I2Cdev/ -ILibraries/IR/ -ILibraries/LiquidCrystal/ -ILibraries/MCP23017/ -ILibraries/MCP23S17/ -ILibraries/MFRC522/ -ILibraries/Mirf/ -ILibraries/MMA_7455/ -ILibraries/OneWire/ -ILibraries/RCSwitch/ -ILibraries/RF24/ -ILibraries/SDCard/ -ILibraries/Servo/ -ILibraries/si4432/ -ILibraries/SI7021/ -ILibraries/SparkFun_APDS9960/ -ILibraries/TFT_ILI9163C/ -ILibraries/Ultrasonic/ -ILibraries/WS2812/ -Ithird-party/spiffs/src -Ithird-party/http-parser/ -Ithird-party/ws_parser/ -Igdb -Isystem/include -Isystem/helpers/include -IWiring/include -Iappinit/include -ISmingCore//include -ISmingCore/Network//include -ISmingCore/Network/Http//include -ISmingCore/Network/Http/Stream//include -ISmingCore/Network/Http/Websocket//include -ISmingCore/Platform//include -IServices/ArduinoJson//include -IServices/CommandProcessing//include -IServices/cWebsocket//include -IServices/DateTime//include -IServices/FATFS//include -IServices/HexDump//include -IServices/libemqtt//include -IServices/SpifFS//include -IServices/WebHelpers//include -IServices/Yeelight//include -ILibraries/Adafruit_BME280_Library//include -ILibraries/Adafruit_GFX//include -ILibraries/Adafruit_ILI9341//include -ILibraries/Adafruit_NeoPixel//include -ILibraries/Adafruit_PCD8544//include -ILibraries/Adafruit_Sensor//include -ILibraries/Adafruit_SSD1306//include -ILibraries/Adafruit_ST7735//include -ILibraries/AM2321//include -ILibraries/APA102//include -ILibraries/ArduCAM//include -ILibraries/BH1750FVI//include -ILibraries/BMP180//include -ILibraries/Bounce//include -ILibraries/CapacitiveSensor//include -ILibraries/DHT//include -ILibraries/DS18S20//include -ILibraries/DS3232RTC//include -ILibraries/HMC5883L//include -ILibraries/I2Cdev//include -ILibraries/IR//include -ILibraries/LiquidCrystal//include -ILibraries/MCP23017//include -ILibraries/MCP23S17//include -ILibraries/MFRC522//include -ILibraries/Mirf//include -ILibraries/MMA_7455//include -ILibraries/OneWire//include -ILibraries/RCSwitch//include -ILibraries/RF24//include -ILibraries/SDCard//include -ILibraries/Servo//include -ILibraries/si4432//include -ILibraries/SI7021//include -ILibraries/SparkFun_APDS9960//include -ILibraries/TFT_ILI9163C//include -ILibraries/Ultrasonic//include -ILibraries/WS2812//include -Ithird-party/spiffs/src/include -Ithird-party/http-parser//include -Ithird-party/ws_parser//include -Igdb/include -Iinclude -Isystem/include -IWiring -ILibraries -ISmingCore -I/home/slavey/dev/esp8266.dev.box/Espressif/sdk//../include -Ithird-party/rboot -Ithird-party/rboot/appcode -Ithird-party/spiffs/src -Ithird-party/http-parser/ -Ithird-party/ws_parser/ -Ithird-party/esp-open-lwip/include -I/home/slavey/dev/esp8266.dev.box/Espressif/sdk//include -I/home/slavey/dev/esp8266.dev.box/Espressif/sdk//include/json -DSDK_PWM_PERIOD_COMPAT_MODE=1 -Wpointer-arith -Wundef -Werror -Wl,-EL -nostdlib -mlongcalls -mtext-section-literals -finline-functions -fdata-sections -ffunction-sections -D__ets__ -DICACHE_FLASH -DARDUINO=106 -DCOM_SPEED_SERIAL=115200 -DENABLE_CMD_EXECUTOR=1 -DESP8266=1 -DSMING_INCLUDED=1  -Os -g -DPROGMEM_L32="__attribute__((aligned(4))) __attribute__((section(\".irom.text\")))" -mforce-l32 -DCUST_FILE_BASE=DateTime -DDEBUG_VERBOSE_LEVEL=2 -DDEBUG_PRINT_FILENAME_AND_LINE=0 -fno-rtti -fno-exceptions -std=c++11 -felide-constructors  -E Services/DateTime/DateTime.cpp -o out/build/Services/DateTime//DateTime.o
```
And then you need open `out/build/Services/DateTime//DateTime.o` and see the result from the pre-processor.

**Pull request merged**
