### PR TITLE
TheaterChase modify

### PR DESCRIPTION
**Pull request by flexiti**
I suggests the last change ..if you have a circle of 16 LED.
So far it is divided by three, it causes the lights 16 and 1 are ON at the same time.

### CODE REVIEW

**Comment by flexiti** [comment]
@alonewolfx2 
I suggest to publish in develop that version. Some have 16xNeo in a circle and then optically it looks worse (16 is not divisible by 3 - LED 1 is ON together with LED 16
 (eg.  @robotiko have). What do You think about it ?

**Comment by alonewolfx2** [comment]
i dont have led ring yet. its working good on ledstript

**Comment by flexiti** [comment]
@alonewolfx2 
This version will work good on ledstrip and ring

**Comment by hreintke** [comment]
@flexiti : @alonewolfx2 :  @robotiko 
Can you update on status ?

**Comment by alonewolfx2** [comment]
@hreintke it can merge. working good.

**Comment by hreintke** [comment]
@alonewolfx2 : 
Then please do and finalize the feature branch in order to keep the repo clean

**Pull request merged**
