### PR TITLE
Fix samples location on CI system.

### PR DESCRIPTION
**Pull request by slaff**

### CODE REVIEW

**Comment by mikee47** [comment]
I think it would be preferable to add `python-requirements` to each sub-make for the `make samples` target. Less of a hack!

**Comment by slaff** [comment]
> I think it would be preferable to add python-requirements to each sub-make for the make samples target. Less of a hack!

I agree with you. Do you want to add a quick PR with that change?

**Comment by mikee47** [comment]
I'm out ATM but can incorporate this into my `update/getting-started` branch, which I hope to push later today.

**Comment by slaff** [comment]
> I'm out ATM but can incorporate this into my

Great! Thanks a lot.

**Comment by slaff** [comment]
Superseded by #2204

**Pull request closed without merging**
