### PR TITLE
Fixed compilation of two samples:

### PR DESCRIPTION
**Pull request by slaff**
* ArduCam
* Basic_WebSkeleton

### CODE REVIEW

**Comment by anakod** [comment]
I think everything is fine.

**Comment by slaff** [comment]
@anakod 

> I think everything is fine.
Great. Meanwhile I will create another PR with changed .travis script to prevent accepting changes that do not compile. This way we can notice earlier if something is wrong.

**Comment by anakod** [comment]
Yes, it will be great too.

**Comment by slaff** [comment]
RTOS migration summary: 
* ArduCam is not present in SmingRTOS -> no need for migration.
* WebSkeletonApp already has the fix although in a different file (configuration.h instead of configuration.cpp). -> no need for migration

**Pull request merged**
