### PR TITLE
m_printf guard against overflow for %s +snprintf

### PR DESCRIPTION
**Pull request by ADiea**
* Fix for #408 
* Implements snprintf
* Fix Makefile for SDK 1.5 (libcrypto required) 
* Fix Makefile for the case MODULES and EXTRA_INCDIR already defined in user Makefile

### CODE REVIEW

**Comment by raburton** [comment]
These would have been preferable as separate prs, so they can be judged and merged separately. For example merging this PR will make Sming require sdk v1.5, a decision on support for which in the next Sming version is still being discussed.

**Comment by ADiea** [comment]
you're right i have removed the dependency

**Comment by ADiea** [comment]
let me know if anything else needed for merging this

**Comment by alonewolfx2** [comment]
are this changes necessary?
```
MODULES 	+= app  # if not initialized by user 
+EXTRA_INCDIR    += include $(SMING_HOME)/include $(SMING_HOME)/ $(SMING_HOME)/system/include $(SMING_HOME)/Wiring $(SMING_HOME)/Libraries $(SMING_HOME)/SmingCore $(SDK_BASE)/../include $(SMING_HOME)/rboot $(SMING_HOME)/rboot/appcode
 ```

**Comment by ADiea** [comment]
@alonewolfx2 yes, this is needed in case the application has already defined MODULES and/or EXTRA_INCDIR. In case they are not defined += will behave like = or ?= I can exclude those and make a different PR if you think appropiate,

**Comment by raburton** [comment]
Please have a look at Makefile-rboot.mk too, any changes made in one of these two make files usually needs to be made in the other as well.

**Comment by ADiea** [comment]
i will revert all changes to he makefile and make a new pr with both the makefiles regarding this separate issue then

**Comment by ADiea** [comment]
let me know if anything else needed for merging this

**Comment by hreintke** [comment]
closing & reopening to force a travis rebuild

**Comment by hreintke** [comment]
@ADiea : 
I will merge this PR but..
In this and the initial PR you updated the esp_systemapi.h to include m_print.
I think it better to create a m_print.h . Then the implementation is similar to other added functionality.
Can you create a PR for that to ?

**Comment by ADiea** [comment]
Sure will move the prototypes to a new file

**Pull request merged**
