### PR TITLE
Expand host tests

### PR DESCRIPTION
**Pull request by mikee47**
Add tests for base64, datetime, http, url, serial, string and objectmap.

(Bunch of test code I had kicking about from earlier PRs.)

### CODE REVIEW

**Comment by mikee47** [comment]
Codacy warning is false positive

**Comment by mikee47** [comment]
Nope, even telling codacy the variable type it still complains. Code works as intended.

**Comment by slaff** [comment]
@mikee47 As far as I can see codacy is complaining about the unused variable named `value`. Which seems to me indeed unused.

image

**Comment by mikee47** [comment]
Setting `value = new TestClass;` invokes the `TestMap::Value` assignment operator which adds the new TestClass instance to the map. If it was truly unused then how could the map count be updated?

**Pull request merged**
