### PR TITLE
Update sample documentation, hot-tips and rboot doc path fix

### PR DESCRIPTION
**Pull request by mikee47**

### CODE REVIEW

**Comment by slaff** [comment]
The doxygen documentation is not showing correctly:
https://sming.readthedocs.io/en/latest/api/index.html 

It is reproducible locally. 

@mikee47  Can you take a look at this when you time?

**Comment by mikee47** [comment]
It seems OK (ish) to me, any specific issue?

**Comment by slaff** [comment]
Well, where is the actual API documentation? No sidebar, no content apart from the default one. I am getting this page:

image

What am I doing wrong?

**Comment by mikee47** [comment]
See top left - drop-down menus. Change was made in #1783 specifically so it could be read on mobile devices (e.g. tablet).

**Comment by slaff** [comment]
Oh... I see now. Thanks for the hints.

**Comment by mikee47** [comment]
It's not brilliant, best I could come up with at the time!

**Pull request merged**
