### PR TITLE
SMTP Sample inital commit

### PR DESCRIPTION
**Pull request by frankdownunder**
Hi Slaff,
Here is my working SMTP send an email sample code.
There are a few issues with this code - but at least its a start.

### CODE REVIEW

**Comment by slaff** [comment]
@frankdownunder Thanks for the efforts. The code at its current state is far from perfect. Here are some remarks from my side.

Move the samples/SMTP/app/smtp.cpp to SmingCore/Network/SmtpClient.cpp.
Apply the same to the smtp.h -> SmingCore/Network/SmtpClient.h.
Remove creation of global instances like `extern smtpClient smtp;`.
Remove debug code like `void displaySessionId(SSL *ssl)`.
Rename the class from `smtpClient` to `SmtpClient` to follow our coding style guidelines.
`WDT.alive();` code is not needed and must be removed unless the client is doing some time consuming calculation.
The hard-coded values should be removed and replaced with variables.
A code like this 
```
while (!client->available())
{
    delay(1);
```
even if it is commented out shows a lack of understanding how an async code/programming is working.

Concerning the code below:
```
void smtpClient::createClient(const String&  smtp_server, int smtp_port)
{
	client = new TcpClient(TcpClientCompleteDelegate(onClientComplete), TcpClientDataDelegate(onReceive));
#ifdef ENABLE_SSL	
```
The code above is more appropriate for a SmtpServer and not a client. Please make the SmtpClient class extend from the TcpClient class.

**Comment by frankdownunder** [comment]
All good, will make those changes.

**Comment by frankdownunder** [comment]
Hi Slaff,
Its better than it was - can you take a look and see what you think now?
Do you need a new PR?

**Comment by slaff** [comment]
@frankdownunder Please, fix the Codacy issue first (https://app.codacy.com/app/slaff2/SmingOfficial/pullRequest?prid=1231750). Just set initial default value for the SMTP port.

> Do you need a new PR?

No, I can see the changes here so it is fine this way.

**Comment by frankdownunder** [comment]
Done.  

Sent from Mail for Windows 10

**Comment by slaff** [comment]
A new and powerful SmtpClient will land in the next 3.6.0 version. The code will come from: https://github.com/slaff/Sming/tree/feature/smtp-client.

**Pull request closed without merging**
