### PR TITLE
Refactor creation of libmain

### PR DESCRIPTION
**Pull request by aemseemann**
Several components in the ESP8266 arch require slight modifications of libmain, e.g. 
- rboot: weaken symbol `Cache_Read_Enable_New`
- custom_heap: remove object `mem_manager.o` 
- Sming core for ESP8266: remove object `time.o`, because its functions are provided by the framework and would otherwise lead to multiple defined references.

The current libmain modification logic is spread across several Makefiles and tailored exactly to the uses described above, which makes it rather hard to maintain or extend.
This PR introduces a more flexible approach and in turn removes the undesired coupling of these components.

### CODE REVIEW

**Comment by slaff** [comment]
@aemseemann Please, fix the failing AppVeyor test: https://ci.appveyor.com/project/slaff/sming-sb483/builds/28736412/job/7w3htx4uvpq8mbaq

**Comment by aemseemann** [comment]
Fixing AppVeyor is easier said than done :(
At first, I suspected the issue is related to the different make versions used on Travis/Ubuntu (4.1) vs. AppVeyor (3.82). But even after building the older version from source, I could not reproduce the error, at least not on a Linux host.

I need to get my hands on a Windows machine first before investigating this any further.

**Comment by mikee47** [comment]
@aemseemann I'll take a look, give me a mo.

**Comment by aemseemann** [comment]
Correction: AppVeyor is using make version 3.8**1** and it *is* the reason for the build failure, since the multi-line variable feature I am using here was only introduced in 3.82.

@slaff: Do we have to stick with this ancient make version on AppVeyor?

**Comment by mikee47** [comment]
@aemseemann I've suggested an alternative approach, pushed to your repo.

**Comment by aemseemann** [comment]
@mikee47: Thank you very much! That did the trick. 
Although list-config doesn't expand the variables (`LIBMAIN_COMMANDS = $(RBOOT_LIBMAIN_COMMANDS) $(APP_LIBMAIN_COMMANDS)`) the expansion seems to work during the actual build.

**Comment by mikee47** [comment]
> Although list-config doesn't expand the variables (`LIBMAIN_COMMANDS = $(RBOOT_LIBMAIN_COMMANDS) $(APP_LIBMAIN_COMMANDS)`) the expansion seems to work during the actual build.

Sorry, I should have taken that out - it's not terribly helpful!

**Comment by mikee47** [comment]
I like this PR, good job thank you!

**Pull request merged**
