### PR TITLE
Feature/httpserver basicauth

### PR DESCRIPTION
**Pull request by patrickjahns**
I took the example from #585 and added it as a feature. 

Interface provides for authentication with either username, password and username+password

If you pass a nullpointer instead of the response pointer, it is possible to create a custom response 

The example application shows each use case.

Comments/Suggestions?

### CODE REVIEW

**Comment by hreintke** [comment]
@patrickjahns : 
First thought and as always open for remarks.
I would make the HttpRequest::isAuthenticated without the httpresponse.
The application has to check/on the result anyway and act accordingly.
I saw a HttpResponse::authorizationRequired() method on which (I think) is not further implemented.
If we handle that correctly the application can do 
if request.isAuthenticated(us,pw) then {response.authorizationRequired() ;return;)

**Comment by patrickjahns** [comment]
@hreintke 
thanks for the great remarks - you are right that is a cleaner way of handling it. Will change the code and update the examples accordingly

**Comment by patrickjahns** [comment]
@hreintke

updated the PR with your suggestions - also added `HttpResponse::setStatus(String statusline)` and `HttpResponse::setStatus(int code, String msg = "")` for custom response example to be illustrated

**Comment by henriquesgsbr** [comment]
I'm trying to compile the example HttpServer_Authorization, 
, this giving the following errors:

C+ app/application.cpp
AR out/build/app_app.a
LD out/build/app.out
out/build/app_app.a(application.o): In function `String::operator+=(char const*)':
/opt/Sming/Sming/SmingCore/Boards.h:17: undefined reference to `HttpRequest::isAuthenticated(String, String)'
/opt/Sming/Sming/SmingCore/Boards.h:17: undefined reference to `HttpRequest::isAuthenticated(String, String)'
out/build/app_app.a(application.o): In function `onPassword(HttpRequest&, HttpResponse&)':
/opt/Sming/Sming/SmingCore/Boards.h:17: undefined reference to `HttpRequest::isAuthenticated(String, String)'
out/build/app_app.a(application.o): In function `onUsername(HttpRequest&, HttpResponse&)':
/opt/Sming/Sming/SmingCore/Boards.h:17: undefined reference to `HttpRequest::isAuthenticated(String, String)'
out/build/app_app.a(application.o):(.text._Z15onCustomHandlerR11HttpRequestR12HttpResponse+0x20): undefined reference to `HttpResponse::setStatus(String)'
out/build/app_app.a(application.o):(.text._Z15onCustomHandlerR11HttpRequestR12HttpResponse+0x4d): undefined reference to `HttpRequest::isAuthenticated(String, String)'
out/build/app_app.a(application.o):(.text._Z15onCustomHandlerR11HttpRequestR12HttpResponse+0x71): undefined reference to `HttpResponse::setStatus(String)'
collect2: error: ld returned 1 exit status
/opt/Sming/Sming/Makefile-project.mk:279: recipe for target 'out/build/app.out' failed
make: *** [out/build/app.out] Error 1

CONSTRUIR FAILED (valor de saída 2, tempo total:  1s)

I'm starting to use sming now, I have very little knowledge of the framework.

Can someone help me solve this build problem?

**Comment by slaff** [comment]
Authentication for Http resources should be based on the upcoming Http refactoring (#1112)

**Pull request closed without merging**
