### PR TITLE
Fix OTA. Disable interrupts during flash erase/write

### PR DESCRIPTION
**Pull request by etmmahi**
Update the patch file for rboot.
This disables interrupts during flash erase/write operations during OTA updates

### CODE REVIEW

**Comment by etmmahi** [comment]
See issue #1520

**Comment by slaff** [comment]
@petrynchyn @Ph3r0x Can you check if this PR is fixing the problem that you are having with OTA?

**Comment by slaff** [comment]
@etmmahi In SDK 1.5 `ETS_SDIO_INUM` does not seem to be defined? Can you update the code set the right definition, if not already defined?

```
/home/travis/build/SmingHub/Sming/Sming/third-party/rboot/appcode/rboot-api.c:71:15: note: in expansion of macro 'FLASH_INT_MASK'
  ets_isr_mask(FLASH_INT_MASK);
               ^
/home/travis/build/SmingHub/Sming/Sming/third-party/rboot/appcode/rboot-api.c: In function 'rboot_write_flash':
/home/travis/build/SmingHub/Sming/Sming/third-party/rboot/appcode/rboot-api.c:31:31: error: 'ETS_SDIO_INUM' undeclared (first use in this function)
 #define FLASH_INT_MASK ((1 << ETS_SDIO_INUM) | (1 << ETS_GPIO_INUM) | (1 << ETS
                               ^
/home/travis/build/SmingHub/Sming/Sming/third-party/rboot/appcode/rboot-api.c:161:17: note: in expansion of macro 'FLASH_INT_MASK'
    ets_isr_mask(FLASH_INT_MASK);
                 ^
make[1]: *** [out/build//home/travis/build/SmingHub/Sming/Sming/third-party/rboot/appcode/rboot-api.o] Error 1
make[1]: Leaving directory `/home/travis/build/SmingHub/Sming/samples/Accelerometer_MMA7455'
make: *** [Accelerometer_MMA7455] Error 2
The command "make samples" exited with 2.
```

**Comment by slaff** [comment]
So the code changes are workaround for the following problem:  
There is, or are, interrupt routines that are not in IRAM. It would be better to find these routines and fix them. Can you paste here the watchdog reset stack dump? Maybe in it stays the name of the function that is causing the issue.

**Comment by etmmahi** [comment]
Correct. This exactly the problem.  By playing with the flags in the interrupt  it is easy to pinpoint the problem. If I leave out the UART bit, the OTA fails! So somewhere in the UART interrupt chain which is executed in the interrupt, there is a function NOT in IRAM. Just find it :-;

**Comment by andr2000** [comment]
Hm, in the rboot example we have serial callback... which is in flash... and is called from the interrupt handler... Can it be why we fail?

**Comment by etmmahi** [comment]
Just did some more experiments. It seems the 'printing' just before the OTA update is causing problems. There is still serial output + interrupts going on when the OTA code is activated. This means there is something in the serial interrupt chain not in IRAM. When we cannot solve this, the workaround with disable interrupts is a good fix,

**Comment by andr2000** [comment]
@etmmahi the strings we print reside in flash and uart_write has the following comment:
`		// If TX buffer not in use or it's empty then write directly to hardware FIFO`
Can it be that we are trying to touch flash while we shouldn't?

**Comment by slaff** [comment]
> If I leave out the UART bit, the OTA fails! So somewhere in the UART interrupt chain ...

@mikee47 When you have some time can you check what can be the issue with the modified UART? There most probably is an IRQ function that is not in IRAM.

**Comment by mikee47** [comment]
@slaff I traced through the interrupt path again last night, and all code is either IRAM_ATTR or __forceinline. I have a suspicion the problem is more subtle or we'd have seen this sooner. I'll think on this!

**Comment by etmmahi** [comment]
Fix #1610 tested, it supersedes this pull request. Closing this one

**Comment by Ph3r0x** [comment]
@slaff sorry for my late response
i've updated Sming with:
make dist-clean
make DEBUG_VERBOSE_LEVEL=3 ENABLE_SSL=1

and i am still getting resettet after a few seconds
my fix for that is the following:
init_method{
...
	// Setup the WIFI connection
	WifiAccessPoint.enable(false);
	WifiStation.enable(true);
	WifiStation.config(WIFI_SSID, WIFI_PWD);

	WifiEvents.onStationGotIP(connectOk);
}

void connectOk(IPAddress ip, IPAddress mask, IPAddress gateway){
	Serial.setCallback(serialCallBack);
}

i dont know but is make dist-clean and make again enough to get the latest develop commit?

**Comment by mikee47** [comment]
> is make dist-clean and make again enough to get the latest develop commit?
@Ph3r0x `git checkout develop`, then `git pull` first

**Pull request closed without merging**
