### PR TITLE
Feature: rbpf containers

### PR DESCRIPTION
**Pull request by slaff**
This PR adds support for rBPF in Sming.
rBPF provides a minimal virtual machine for microcontrollers.
rBPF is a virtual machine based on the popular Linux BPF virtual machine.
It is small and fast enough to host multiple instances on architectures targeted by Sming.

Related to #2419.

### CODE REVIEW

**Comment by mikee47** [comment]
I'm looking at how to get this working on Windows. Clang is already present on appveyor (and is easiily installed using `winget install llvm`) so can generate the bytecode, but still looking for the system compiler to generate BPF object code...

**Comment by mikee47** [comment]
Don't need LLC at all, can use Clang directly! Fix coming...

**Comment by mikee47** [comment]
@slaff Pushed a PR to your repo which fixes Windows build. Got another PR ready with Store support.

**Comment by slaff** [comment]
> Got another PR ready with Store support.

Send it to me :)

**Pull request merged**
