### PR TITLE
Update ds18s20.cpp negative temperature bug.

### PR DESCRIPTION
**Pull request by Ogyb**
Negative temperature bug!

Deleted actualy and added code:
```
int16_t raw = data[0] + ((data[1] & 0x07) << 8);
if(data[1] >= 8) raw = raw - 0x0800;
```

### CODE REVIEW

**Comment by slaff** [comment]
@Ogyb Can you provide test cases? Values that are causing this issue, way to test it ourselves, etc.

**Comment by flexiti** [comment]
I am using it a year and seams that negative was ok.
How You read temeperature ?? 
What about lines below:

```
201    if (raw & 0x8000)   //is minus ?
202	  celsius[numberOfread] = 0 - ((float) ((raw ^ 0xffff) + 1) / 16.0); // 2's comp
203	else
204	  celsius[numberOfread] = (float)raw / 16.0;	
```

**Comment by Ogyb** [comment]
Actually is:

`unsigned int raw = (data[1] << 8) | data[0];`

if DS read data (0550h) (85C by Datasheet) and "raw / 16" (celsius conversion) give 85.00 - its OK
and if read data (FFF8h) (-0,5C by Datasheet) and "raw/16" give 268435456.00 - its no ok!

I changed to (This no in float and 16b signed int not 32b):
```
int16_t raw = data[0] + ((data[1] & 0x07) << 8);
if(data[1] >= 8) raw = raw - 0x0800;
```
 
and if read data (FFF8h) (-0,5C by Datasheet) and "raw/16" give -0.50 - its OK

**Comment by flexiti** [comment]
@Ogyb 
Pls check rest of code  and #486

**Comment by Ogyb** [comment]
Ok sorry - i update my libary by "Chocoletly" and this not code on GitHub;) It's ok, this Code working correctly.

**Comment by uzi18** [comment]
Why not use union and conversion is out of the box...

05.01.2017 3:42 PM "Ogyb" <notifications@github.com> napisał(a):

**Comment by flexiti** [comment]
@uzi18 
for what ? 99.9% application is temperature reading only

**Comment by uzi18** [comment]
For nice source readout and simplify.

05.01.2017 4:58 PM "flexiti" <notifications@github.com> napisał(a):

**Pull request closed without merging**
