### PR TITLE
Fix the latest Travis builds failing with error: invalid command 'bdi…

### PR DESCRIPTION
**Pull request by slaff**
…st_wheel'

### CODE REVIEW

**Comment by mikee47** [comment]
@slaff We should probably take this opportunity to migrate to `travis.ci.com`
https://docs.travis-ci.com/user/migrate/open-source-repository-migration#q-when-will-the-migration-from-travis-ciorg-to-travis-cicom-be-completed

**Comment by mikee47** [comment]
@slaff Reckon I've got this cracked. See #2180

**Comment by slaff** [comment]
Closing in favour of #2180.

**Comment by mikee47** [comment]
> 
> 
> @slaff We should probably take this opportunity to migrate to `travis.ci.com`
> https://docs.travis-ci.com/user/migrate/open-source-repository-migration#q-when-will-the-migration-from-travis-ciorg-to-travis-cicom-be-completed

Need to sign up to Beta program (requires admin) https://travis-ci.com/organizations/SmingHub/migrate

**Pull request closed without merging**
