### PR TITLE
Pr732

### PR DESCRIPTION
**Pull request by slaff**
Rebase of #734. 

Notes: We need to evaluate the pros and cons of dynamic allocation for this specific case(introduced with **"Optimize stack usage"** commit  b9b7e69):
* Pros: Less initial heap usage.
* Cons: Heap Fragmentation.

### CODE REVIEW

**Comment by ADiea** [comment]
Given that this *could* be used quite frequently during application lifecycle(ex when data arrives from sensors and timestamp is generated) I would keep it on stack
But it all depends on application usage. It will not eat from initial RAM.

On the other hand, if we also m,erge the custom memory alloc ummalloc which does best fit allocation, allocating on heap might work. 
Bonus for using ummalloc: you can set custom callback in case mem alloc fails so you don't have to check always the pointer retrurned by new which will save you some code. (in this commit checking is not done)

**Comment by slaff** [comment]
@ADiea thank you for the well-reasoned opinion. 

My plan is to release the next version before or on Christmas so I will wait until 21of December before I start with the final preparations.

**Comment by slaff** [comment]
Custom Heap with UMM Malloc can also be part of the new release:  #835

**Comment by ADiea** [comment]
Offtopic: @slaff thanks for latest work reviving sming nonos. 

I'm currently waiting for new pcbs and will start resynching my local branch of sming to the latest when I will have new hardware assembled. I think that the 3rd party additions is the most powerfull change that will provide better maintainability in the future!

**Comment by slaff** [comment]
>  I think that the 3rd party additions is the most powerfull change that will provide better maintainability in the future!

@ADiea Glad to hear that! I am waiting also for great new additions from your local branch :)

**Pull request merged**
