### PR TITLE
Upgrade to FlashString Library v2.0.0

### LINKED ISSUE #1952: FlashString incompatible with ArduinoJson 6.13.0
Sming currently uses [ArduinoJson 6.12](https://arduinojson.org/2019/09/05/version-6-12-0/).

[Version 6.13](https://arduinojson.org/2019/11/01/version-6-13-0/) has been released, however it is not currently compatible with FlashStrings. See https://github.com/bblanchon/ArduinoJson/issues/1126.

I'm working on an update to FlashString, with improvements to table support and the addition of associative maps, i.e. `Key => Value` structures stored directly in flash.

### PR DESCRIPTION
**Pull request by mikee47**
I've pulled out FlashString.h into a separate Component and constructed a library from it.
Plus a few little upgrades.

Fixes #1952.

Pre-built documentation can be found at https://smingdev.readthedocs.io/en/latest/_inc/Sming/Components/FlashString/index.html.

Travis integration tests are packaged into the library, which pulls in Sming from the develop branch in my own repo. This allows me to merge any necessary changes to Sming (i.e. this PR) and check it as a package.

CI tests here https://travis-ci.org/mikee47/FlashString

### CODE REVIEW

**Comment by slaff** [comment]
This seems like a big refactoring. @mikee47 Did you have the time to check the changes on a real device with multiple samples?

**Comment by mikee47** [comment]
@slaff Yes, of course. Just as well you checked with me as it did throw up two little bugettes! Have re-compiled, flashed and checked the following applications on a nodeMCU:

- Revised Basic_WebSkeletonApp sample (both SPIFFS and non-SPIFFS modes)
- Basic_ProgMem: Contains updates to custom object creation and table handling. Bugfix: Forgot to put custom array data in PROGMEM!
- HostTests: I added specific tests for the changed functions in HttpCommon.cpp and HttpHeaders.cpp.
- FlashString test application: Contains extended tests for the library. Bugfix: Invalidate check was wrong.

I'll push updates for these.

**Comment by mikee47** [comment]
If you would like me to split this PR up that's fine.

**Comment by slaff** [comment]
@mikee47 There is some instability. I cannot say right now if this PR is the culprit or earlier ones. But it seems that always a String operation is involved in the segfaults. Example excerpt:

```
0x4024aef9: String::String(char const*) at /path/to/Sming/Sming/Wiring/WString.cpp:823 (discriminator 3)
0x40240000: String::buffer() at /path/to/Sming/Sming/Wiring/WString.h:486
 (inlined by) String::begin() at /path/to/Sming/Sming/Wiring/WString.h:401
 (inlined by) CStringArray::add(char const*, int) at /path/to/Sming/Sming/Core/Data/CStringArray.cpp:36
0x4023faac: fileExist(String const&) at /path/to/Sming/Sming/Core/FileSystem.cpp:99
0x4024aef9: String::String(char const*) at /path/to/Sming/Sming/Wiring/WString.cpp:823 (discriminator 3)
```

The problem is caused by fileExist checking the existence of a normal spiffy file. Spiffs are mounted correctly. 

This might to related also to another reported issue: https://github.com/SmingHub/Sming/pull/1817#issuecomment-552633689

**Comment by slaff** [comment]
I can confirm now that the instability is due to the SSO commit: https://github.com/SmingHub/Sming/commit/1fb600ec38241d83b7a60dce2fb95698a98bd1b6. I will check if the problems are reproducible under the Host architecture and see what valgrind will report.

**Comment by mikee47** [comment]
I'm trying to reproduce the issue and track it down via the debugger

**Comment by mikee47** [comment]
So far I cannot reproduce this problem. I note that CStringArray could be implicated, so I'll check that next.

**Comment by mikee47** [comment]
I've drawn a blank. If you can tell me how to reproduce the problem I can fix it, but otherwise I'll just leave it for now.

**Comment by mikee47** [comment]
Re. the codacy advisory about PROGMEM, I'm sure I've seen that one before. Is there any way to tell Codacy what PROGMEM is?

**Comment by slaff** [comment]
> Is there any way to tell

I will ignore the false issue. And check if I can add you also to the members of the codacy team.

**Comment by slaff** [comment]
Here is how you can reproduce it.
0. Go to the problematic commit 

  cd %SMING_HOME%
  git checkout 1fb600e

1. Go to the Basic_rBoot sample.
2. Compile it with
   
     make DEBUG_VERBOSE_LEVEL=3

3. Flash it on the device. Power off and on, if needed.
4. Connect to the device

     make terminal

5. Type `help`, followed by `ls`. And boom:

```
pm open,type:2 0
E:M -1
vPortFree 517 line assert fail
E:M -1
E:M -1
E:M -1
E:M -1
filecount 1952984696


***** Fatal exception 28 (LOAD_PROHIBITED)
pc=0x40237580 sp=0x3ffffee0 excvaddr=0x00000014
ps=0x00000030 sar=0x00000000 vpri=0x3ffe890c
r00: 0x402375dd=1076065757 r01: 0x3ffffee0=1073741536 r02: 0x0000000c=        12 
r03: 0x0000000c=        12 r04: 0x74682e78=1952984696 r05: 0x00000000=         0 
r06: 0x0000007e=       126 r07: 0x00000193=       403 r08: 0x6000001c=1610612764 
r09: 0x3ffffea0=1073741472 r10: 0x3ffe88fe=1073645822 r11: 0x0000007f=       127 
r12: 0x0000000c=        12 r13: 0x3ffef154=1073672532 r14: 0x3ffef154=1073672532 
r15: 0x3fffff10=1073741584 

```

**Comment by mikee47** [comment]
@slaff Can I just check what compiler version you're on?

```
$ESP_HOME/xtensa-lx106-elf/bin/xtensa-lx106-elf-gcc --version
```

**Comment by mikee47** [comment]
I've tested against the commit you specified, and also with this PR and no issues. That's in Windows GCC 5.2.0. I'll try in Linux, that's GCC 4.8.5.

**Comment by slaff** [comment]
> $ESP_HOME/xtensa-lx106-elf/bin/xtensa-lx106-elf-gcc --version

xtensa-lx106-elf-gcc (crosstool-NG crosstool-ng-1.22.0-55-gecfc19a) 4.8.5
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by slaff** [comment]
> no issues. 

Ok, I have tried again with new clean clone and same compiler.  The issue is still there. I am attaching also the generated files. 
[basic_rboot.out.zip](https://github.com/SmingHub/Sming/files/3869951/basic_rboot.out.zip)

**Comment by mikee47** [comment]
I have it running in Linux, with the same error as you. Investigating...

**Comment by mikee47** [comment]
OK, fixed with #1977.

**Comment by mikee47** [comment]
This raises another issue that whilst running HostTests via CI is all very well, it also needs to be run on real hardware. I've been doing this in Windows, naively assuming it'd be OK in Linux...

**Comment by mikee47** [comment]
I've built and run the integration tests for FlashString under Linux (with the String fix applied) and it's fine.

**Comment by mikee47** [comment]
I've taken out commit to `Deserialize JSON FlashStrings using a stream` as there's a better way in 6.13 and I'll deal with it separately.

**Comment by mikee47** [comment]
I'm reviewing the library documentation, some parts are out of date.

**Comment by slaff** [comment]
@mikee47 Please, rebase.

**Comment by mikee47** [comment]
OK, rebased. I've updated the library with revised documentation.

**Comment by slaff** [comment]
@mikee47 Do you want to add something to this PR or it is ready for me to test :)

**Comment by mikee47** [comment]
@slaff I'm all done now, please proceed!

**Comment by aemseemann** [comment]
@mikee47: I noticed that the new submodule lacks the `ignore = dirty` property in .gitmodules. Is is intentional? 
Although there is no local modification, the submodule always shows up as modified in "git status" due to the ".submodule" file.

**Comment by mikee47** [comment]
@aemseemann Unintentional, thanks for point it out. Will add that to next patch.

**Comment by slaff** [comment]
@mikee47 Do you mind moving FlashString to https://github.com/SmingHub/FlashString? I would prefer to have core components under the SmingHub team.

**Comment by mikee47** [comment]
At some point I'll probably port it for Arduino so intend to keep it platform agnostic. You can always fork it though. Did you intend to pull all the other core submodules in as well?

**Comment by slaff** [comment]
> At some point I'll probably port it for Arduino so intend to keep it platform agnostic.

Ok, then keep it where it is.

> Did you intend to pull all the other core submodules in as well?

If they are pure Sming components and are used in the core - well yes.

**Comment by mikee47** [comment]
> If they are pure Sming components and are used in the core - well yes.

I don't think there are any others - though I notice lwip2 has failed again so might be worth forking to github?

**Comment by mikee47** [comment]
As a C++ framework I feel we should always be keeping an eye out for ways to use the language to our benefit. Related to FlashString, https://github.com/Chris--A/PGMWrap is a very interesting approach to dealing with flash data.

**Pull request merged**
