### PR TITLE
UPnP code generation

### PR DESCRIPTION
**Pull request by mikee47**
Further development to UPnP framework.
Some additions required to the build system to support intermediate code generation.

* Add COMPONENT_PREREQUISITES and COMPONENT_BUILD_BASE to build framework
* Fix `ListAllSubDirs` - should be able to handle multiple arguments
* Add `ListAllFiles` and `dirx`
* Add UPnP-Schema library
* Update SSDP, UPnP, HueEmulator libraries

### CODE REVIEW

**Comment by slaff** [comment]
@mikee47 Ping me when this PR is ready.

**Comment by mikee47** [comment]
@slaff If we wait until #2151 is merged I can test/rebase first.

**Comment by slaff** [comment]
@mikee47 Are you planning further changes to this PR or I should merge it?

**Comment by mikee47** [comment]
@slaff I need to rebase, re-test and confirm behaviour. Will probably have to just accept any quirks for now - did a quick test of #2175 and it made no difference so I need to spend more time trying to reproduce the problem more concisely. It's not a show-stopper though.

**Comment by mikee47** [comment]
@slaff You've fixed the issue with task queues - Thank you! Happy to merge now.

**Pull request merged**
