### PR TITLE
Fix MQTTClient not sending PINGREQ when receiving messages

### PR DESCRIPTION
**Pull request by Informatic**
Suggested fix for #549. Tested, seems to work fine.

### CODE REVIEW

**Comment by hreintke** [comment]
@Informatic : 
Is the PING_REQ used for the keepAlive messages ? 
If so, there is a keepAlive variable in the MqqtClient, can we use that value ?
if not, There is a harcoded 10 seconds in the patch. Can you explain the value ?

**Comment by hreintke** [comment]
Mqtt specs : 
>The MQTT specification says the following:

>It is the responsibility of the Client to ensure that the interval between Control Packets being sent does not exceed the Keep Alive value. In the absence of sending any other Control Packets, the Client MUST send a PINGREQ Packet.

>That means as long as messages are exchanged frequently and the keep alive interval is not exceeded, there is no need to send an extra message to ensure that the connection is still open.

>But if the client doesn’t send any messages during the period of the keep alive it must send a PINGREQ packet to the broker to confirm its availability and also make sure the broker is still available.

>The broker must disconnect a client, which doesn’t send PINGREQ or any other message in one and a half times of the keep alive interval. Likewise should the client close the connection if the response from the broker isn’t received in a reasonable amount of time.

I read this as : If there is a continuous flow of message there is no need to send PING_REC 

There might be a flaw in the handling of keepalive as there is also a harcoded 10 in the current code.
Can you check that too ?

**Comment by Informatic** [comment]
About hardcoded 10 seconds - yes, I think it should be based on keepAlive value, for instance keepAlive/2 (like it was with default 20 second keepAlive value in current `develop` branch) however I wanted to make as little changes as possible to fix that specific issue.

> I read this as : If there is a continuous flow of message there is no need to send PING_REC
Yes, you are right, however the specification talks about packets sent from client to server. When server sends QoS 0 messages client does not send any response for that. (and thus server does not know if client is alive or not and PINGREQ is needed)

**Comment by hreintke** [comment]
@Informatic : 
OK, understand the need for PING.
Can you  extended the patch to handle keepalive without hardcoded values ?

Remarks on that.
In don't understand why we would send PING at a rate of keepAlive/2. Shouldn't that just be keepAlive ?
Can you use parenthesis in the ((lastMessage and (millis() - lastMessage >= 10000)) for readability.
Can you check handling of millis() rollover ?

**Comment by Informatic** [comment]
Changed previous hardcoded 1000ms interval with `keepAlive*1000`, as it seems to be behaviour of python-paho MQTT implementation, which seems to work fine.
Added parenthesis per your suggestion, and changed `and` for `&&` since that looks like a more common version in SmingCore.
millis() rollover is handled properly.

I'll test everything again later this weekend.

**Comment by hreintke** [comment]
Thanks for your effort in this. 
FYI : The appveyor fail is due to the experimental implementation we have there.
What matters is the OK from Travis that a PR doesn't break compilation of other parts.

**Comment by hreintke** [comment]
@Informatic : 
Any results from your testing available ?

**Comment by hreintke** [comment]
@Informatic : 
Can you provide an update on this PR ?

**Comment by Informatic** [comment]
Hi, turns out i don't have enough time to test it thoroughly past two and next two weeks. I only had it running for 30-something minutes and worked well, but more testing might be needed.

**Comment by anakod** [comment]
It's ready for merging, I'm sure.

**Pull request merged**
