### PR TITLE
StationClass::getBCast() and AccessPoint::getBCast() added.

### PR DESCRIPTION
**Pull request by vsirvent**
Add StationClass::getBCast() and AccessPoint::getBCast(). This is usefull when AccessPoint and WifiStation are active at the same time and you want to send broadcast packets throught a specific network interface,

### CODE REVIEW

**Comment by tprochazka** [comment]
PR should contain just one commit, why you have two more with some Merge?

**Comment by vsirvent** [comment]
Hi @tprochazka,

Sorry but I'm not git expert and this is my first PR attempt. I did a merge pull from Sming/develop to my vsirvent/develop fork to get updated develop version then changed the code and then merged from vsirvent/develop to Sming/Develop, but as I see from other PR it's not correct. Shall I work directly with Sming/develop instead my fork?

**Comment by raburton** [comment]
To update your develop branch to latest changes in upstream development branch:
```
git checkout develop
git pull --rebase upstream develop
git push origin develop
```
This avoid unnecessary merges in the logs.

It should still be possible to do this now (back up the 4 files just to be safe), and it will rebase develop and apply your changes to it. When you push it back to github this PR will be updated automatically. If it complains that it can't push back to github add `-f` to the push command.

If you haven't already set an upstream repo for your fork you'll need to do this first:
```
git remote add upstream https://github.com/SmingHub/Sming.git
```

**Comment by raburton** [comment]
And thanks for contributing :-)

**Comment by vsirvent** [comment]
Hi @raburton,

Thanks for your reply. I'll try that this afternoon. Hope I can contribute to the project ;)

**Comment by anakod** [comment]
I think it should be named in standard Sming conversion, like GetBroadcastAddress() or GetBroadcastIP().

**Pull request closed without merging**
