### PR TITLE
MQTT fixes to will, client id, connect to ip, username and password.

### PR DESCRIPTION
**Pull request by slaff**
Tested with the latest Sming develop on real ESP8266.
Credits to #505 for pointing out some of the issues.

### CODE REVIEW

**Comment by slaff** [comment]
Fixes #491.

**Comment by etmmahi** [comment]
This pull request includes the changes of pull request #505 
Pull request #505 can be closed then when this one is merged.

**Comment by hreintke** [comment]
@slaff : 
I would like to merge this commit as mentioned in the PR summary : 
`This branch has conflicts that must be resolved`

Can you check the commit ?

**Comment by slaff** [comment]
@hreintke Should be fine now. I merged the latest develop branch in it.

**Comment by flexiti** [comment]
@hreintke 
Its merged to develop ?

**Comment by flexiti** [comment]
This one is important and tested.
@anakod  @hreintke 
Why is not merged yet to develop?

**Comment by hreintke** [comment]
Because I overlooked the message in the email on this a couple of days ago and did not yet had the "overall action on open PR/issues" this week. :smile: 
Will merge

**Comment by flexiti** [comment]
thanks

**Comment by alonewolfx2** [comment]
@slaff can you make same pr for rtos based sming?

**Pull request merged**
