### PR TITLE
Websockets Command Processing

### PR DESCRIPTION
**Pull request by hreintke**
Squased PR to Develop

### CODE REVIEW

**Comment by hreintke** [comment]
@All 
I am looking for volunteers for testing this added functionality. I like to have this included in the next release.

**Comment by kireevco** [comment]
@hreintke, please come up with a test case, and we can test it

**Comment by alonewolfx2** [comment]
@hreintke @kireevco is right. come up and we can test it.

**Comment by hreintke** [comment]
@All 
Added documentation, currently to main directory but can be changed to other location if needed.

**Comment by hreintke** [comment]
This PR closed, Replace by new, based on latest develop branch

**Pull request closed without merging**
