### PR TITLE
On the fly minification of .css and .js for sming's web server

### PR DESCRIPTION
**Pull request by piontec**
Hi,
This PR contains changes required for on-the-fly generation of SPIFFS images for web server with auto minified and compressed JS and CSS.

Requirements:
 - needs latest spiffy from master branch of [alonewolfx's repo] (https://github.com/alonewolfx2/spiffy)
 - needs yuicompressor (already included in kireevco's [docker image] (https://github.com/kireevco/sming-docker)
 - needs a small change in Makefile-project.mk to read SPIFFS size

Pros:
 - can make SPIFFS images 2-4 times smaller
 - works on-the-fly
 - uses sming's HttpResponse and default ".gz" handling if present, so shouldn't need any modification in html files

I didn't add the changes to the main Makefile, as my makefile-ish is rather poor - use what you like and rewrite as needed

### CODE REVIEW

**Comment by piontec** [comment]
Uhm, actually there's a problem: all other files from web/dev are not copied to output dir - need to fix this

**Comment by kireevco** [comment]
@piontec thank you for you PR. Really nice. I would like to move Makefile-web to sming core, making sure it is backwards compatible with projects taht don't have yuicompressor.

**Comment by anakod** [comment]
Very like it, but what if no yuicompressor was installed in user system? Which dependecies it have, only Java or something else too?

**Comment by ajvb** [comment]
@anakod It's only Java

**Comment by robotiko** [comment]
+1

**Comment by ajaybhargav** [comment]
It would be great to have mechanism for minification of web dev files. Please merge this.

**Comment by kireevco** [comment]
Did anyone see https://pypi.python.org/pypi/css-html-js-minify ? Looks pretty functional.

**Comment by kireevco** [comment]
@piontec I know its been a while, and we still need minification.
We are trying to implement git-flow (#230). Can you please re-submit your PR to a feature branch?
For example _feature/yuicompressor-minification_?
Also, please squash your commits to one.

**Comment by hreintke** [comment]
This issue has been inactive for a long period and is being closed. If the issue is still valid please open a new with complete description

**Pull request closed without merging**
