### PR TITLE
Fixes to Travis CI

### PR DESCRIPTION
**Pull request by mikee47**

### CODE REVIEW

**Comment by slaff** [comment]
@mikee47 I guess the gcc-multilib package for Ubuntu Focal and x86_64 is broken ...

**Comment by slaff** [comment]
@mikee47 I guess we are hitting something similar to this old error: https://bugs.launchpad.net/ubuntu/+source/gcc-10/+bug/1872854

**Comment by slaff** [comment]
Hm.. Travis is working as expected now but Appveyor on Ubuntu started to fail ...

**Comment by mikee47** [comment]
@slaff Thank you for fixing this. What a palava!

**Pull request merged**
