### PR TITLE
Improvements to HostEd

### PR DESCRIPTION
**Pull request by mikee47**
This PR proposes some changes to the Hosted classes

**Update simpleRPC to master**

With clang-tidy #2648 some failures occur in the `simpleRPC` library. Updating this to current master solves the issues.
I've also put all the code into the `simpleRPC` namespace which sorts out the conflict with `Vector` but makes it available for use if required.

**Tidy HostTests module**

Also decode the anonymous 'packet' blob so we can see what's in it and compare with spec. should we wish to update it.

**Use abstract base class for callbacks**

Simplifies implementation since usually all callbacks are required.
Compiler ensures all methods have implementations.
`clang-tidy` gave potential memory leak indication because of Delegates. Not sure if that's real but this fixes it.

### CODE REVIEW

**Comment by slaff** [comment]
@mikee47 I am trying to compile the Basic_Blink using the command below and I get compilation error?!

```
cd $SMING_HOME/../samples/Basic_Blink
make SMING_ARCH=Host ENABLE_HOSTED=tcp HOSTED_SERVER_IP=192.168.4.1
```

The error is: 
```
static_assert(sizeof(time_t) == 8, "Expecting 64-bit time_t");
```

Any idea how to work around this issue?

**Comment by mikee47** [comment]
> ... Expecting 64-bit time_t

I'm going to guess your version of GCC is old; I'm with Fedora on GCC 13.2.1 - what version are you using?

**Comment by slaff** [comment]
>  what version are you using?

Gcc version 9.4.0. I will check if I can upgrade on my Ubuntu 20.04 LTS ...

**Comment by slaff** [comment]
Gcc version 10.5.0 is the latest GCC that I can use ... Hm.. have to think about OS upgrade ...

**Comment by mikee47** [comment]
> Gcc version 10.5.0 is the latest GCC that I can use ... Hm.. have to think about OS upgrade ...

That should be fine https://github.com/SmingHub/Sming/issues/2758

You can just comment out that assert - I put it there deliberately so we'd know about this sort of thing!

**Comment by mikee47** [comment]
@slaff You'll doubtless have run into the other issue attempting to build `Basic_Blink` for Hosted using a `tcp` connection: `DISABLE_NETWORK` is hard-coded in `component.mk` and has to be changed. I'm thinking that's probably just something to bear in mind using Hosted.

**Review by slaff — APPROVED** [review]

**Pull request merged**
