### PR TITLE
New SPI impl. with Arduino style Api - BaseClass, SwSPI, HwSPI  -> Testcase SD Card

### PR DESCRIPTION
**Pull request by harry-boe**
Ok this is a bigger one

New SPI implementation 100% compliant with Arduino HW SPI API.
This eases porting Arduino libs to sming -> in most cases 1:1 

The API is defined by the SPIBase interface, so it can be changed from SW SPI to HW SPI without code mods. See SDCard sample app.

```
//      Software
//	SDCardSPI = new SPISoft(PIN_CARD_DO, PIN_CARD_DI, PIN_CARD_CK, 0);

//      Hardware SPI
	SDCardSPI = new SPIClass();

//      Common
	SDCard_begin(PIN_CARD_SS);

// overwrite default SPI Speed (ignored by SW SPI)
	SDCardSPI->beginTransaction(SPISettings(40000000, MSBFIRST, SPI_MODE0));

```

The API required a new Software SPI implementation. Have teste what  have on Hardware but it requires more test
  
Successful test:  SDCard (The base of the old imply.) ScreentTFT_ST7735, OLED_SSD1306

New HW SPI implementation tested with single byte TX und long buffers (SDCard / ArduCam)
Also tested various frequencies, byte-orders and SPI modes

Includes documentation tags (not sure if they work)

Here are some Benchmarks SW vs HW SPI from the SDCard impl.

```
Software  SPI  SD-Card
4. Write speed benchmark:

Write 1 kBytes in 1 Bytes increment: 17.23 kB/s
Write 1 kBytes in 64 Bytes increment: 17.29 kB/s
Write 1 kBytes in 128 Bytes increment: 17.36 kB/s
Write 1 kBytes in 512 Bytes increment: 17.39 kB/s
Write 1 kBytes in 1024 Bytes increment: 17.90 kB/s
Write 4 kBytes in 1024 Bytes increment: 50.78 kB/s
Write 8 kBytes in 512 Bytes increment: 65.03 kB/s
Write 8 kBytes in 1024 Bytes increment: 73.12 kB/s
Write 8 kBytes in 8192 Bytes increment: 86.05 kB/s

Hw SPI SD-Card

4. Write speed benchmark:

Write 1 kBytes in 1 Bytes increment: 34.26 kB/s
Write 1 kBytes in 64 Bytes increment: 35.45 kB/s
Write 1 kBytes in 128 Bytes increment: 35.33 kB/s
Write 1 kBytes in 512 Bytes increment: 35.46 kB/s
Write 1 kBytes in 1024 Bytes increment: 37.60 kB/s
Write 4 kBytes in 1024 Bytes increment: 108.63 kB/s
Write 8 kBytes in 512 Bytes increment: 125.07 kB/s
Write 8 kBytes in 1024 Bytes increment: 158.91 kB/s
Write 8 kBytes in 8192 Bytes increment: 239.17 kB/s 

40 Mhz Bus Speed !!!

```

### CODE REVIEW

**Comment by alonewolfx2** [comment]
This is bigger one. I will test on sdcard,ili9341 tonight. Thank you for your bigger effort.

**Comment by harry-boe** [comment]
Note: 
The ili9341 is not using this SPI implementation. It includes a own SPI imp. for sending data.
The changes i made on that project was simply updating to the new definitions from api_register.h (SDK 1.5)
The ill9341 might need some cleanup work to get rid of redundant code

**Comment by alonewolfx2** [comment]
@harry-boe i am already trying to cleanup and integrate sming spi driver into the ili9341.I will try with this one.

**Comment by harry-boe** [comment]
Great! I had somewhere a ili9340 display laying around but can'f find it right now.

**Comment by alonewolfx2** [comment]
@harry-boe ili9341 hwspi compiling done. Just need test on hw. I will test this night on hw. But new library need test on a couple example. ex: bmp library.

**Comment by harry-boe** [comment]
@alonewolfx2   i will do the port to rtos once we passed the tests here

**Comment by alonewolfx2** [comment]
test passed on ili9341, there is no compiling or reset problem on other libraries side. also you tested on   ScreentTFT_ST7735, OLED_SSD1306 and sdcard. i think its ready. 
@hreintke i am merging this when i try on mfrc522 too. is it ok ?

**Comment by harry-boe** [comment]
There is still a div zero bug we discovered in the frequency/divider calculation that produces a runtime error with certain frequencies (e.g. 24 MHz) .. will provide  a fix soon.

**Pull request merged**
