### PR TITLE
Patches to allow a clean release

### PR DESCRIPTION
**Pull request by hreintke**
Update Sming Version in master branch

### CODE REVIEW

**Comment by hreintke** [comment]
@kireevco : 
Can you check and update if necessary the information on installation ?

**Comment by hreintke** [comment]
@all : 
Please check whether any other small updates need to be made to master branch in order to define a clean Sming Release.

**Comment by raburton** [comment]
You could fix the several instances of `Build-in`, which isn't a real word, to `Built-in` while you're at it.

**Comment by alonewolfx2** [comment]
also please change this line "[Spiffy] (https://github.com/alonewolfx2/spiffy) sming branch" to "[Spiffy] (https://github.com/alonewolfx2/spiffy) master branch"

**Comment by hreintke** [comment]
OK, I will.
Can you write in your readme of the spiffy repo a remark on the possible issues on compile ?
mingw\bin vs mingw\sys\...

**Comment by raburton** [comment]
Should we take the opportunity of this new release to fix the spiffs bug?

**Comment by hreintke** [comment]
I am a little hesitant on that. If I am correct it will break usage all current users of spiffy.
If that is true maybe we can better communicate upfront and keep the update for next release.
I think we can do a next release in 3-4 weeks so we have a short time to define a correct update strategy.

**Comment by alonewolfx2** [comment]
@hreintke ok.

**Comment by raburton** [comment]
@hreintke ok, I agree too

**Comment by hreintke** [comment]
@kireevco : @piperpilot @alonewolfx2 
A few days ago there was the discussion on binaries in Release.
Conclusion I think was not to include the libsming.a in the release, Mentioned was to update "gitignore" to prevent releasing. I have no experience in that.Can one of you take this action ?

**Comment by raburton** [comment]
@hreintke i've removed libsming.a and added the appropriate .gitignore file (develop branch)

**Comment by hreintke** [comment]
@All : 
Anyone sees another needed update to master branch before creating a formal Sming release in github ?

**Comment by raburton** [comment]
Are we going to pull the changes from develop into master as well for the release?

**Comment by kireevco** [comment]
No direct merges between develop and master should be made.

**Comment by hreintke** [comment]
@raburton @kireevco 
No, nothing from current develop into master now.
I want to create a "first" actual release on Github which is the current master. 
After that, next release, not to far away : 
the process is : when develop has all the intended updated and is tested that will be merged into master to create a new release.
We now have a "develop in progress" 
- some leftovers from "old process" which are PR's untested but merged into develop
I've requested testing on those to be sure they are correct
- some PR's which have been tested in PR status and working OK.

**Comment by hreintke** [comment]
@raburton @kireevco 
Just to be sure on terminology of which my use may not be 100% correct.
I mean to say : all functionality in develop should be moved from develop to master to create the new release.
If that is called/done using (direct) merge or pull request (or other) needs to be decided, based on detailed knowledge of the differences

**Comment by raburton** [comment]
Ok, so develop will normally be merged to master for future releases, but not for this one. Is anyone going through the list of commits that are in develop, but not master, to see which ones should be included in the new release (and if so having to create new PRs against master for them)? Or are we just leaving everything that's currently in develop out of this release?

**Comment by kireevco** [comment]
How will you protect yourself from including something that is being merged to develop at the time of you creating a release? One extra pr merged to develop and your plan won't work.

**Comment by raburton** [comment]
> How will you protect yourself from including something that is being merged to develop at the time of you creating a release? One extra pr merged to develop and your plan won't work.

The normal way is to have a development freeze in preparation for the release. Nothing else is allowed into the development branch once the freeze has started, except fixes to the included content, and once it's deemed stable it's merged to master. Then new development continues in the development branch. The freeze doesn't even stop people working against the development branch in PRs, just they don't get merged until the freeze is over. That's a pretty standard way of doing things.

**Comment by kireevco** [comment]
Yep. Something like release/1.3 branch

**Comment by raburton** [comment]
If you don't intend to do that how do you plan to get new features or fixes into master? Will someone need to diff master and develop, cherry pick the wanted commits in from develop, unpick conflicts from other commits in develop, and recommit them to master?

**Comment by kireevco** [comment]
I feel like cherry picking was the main way of moving things from develop to master.

**Comment by raburton** [comment]
That's a huge waste of time, which I don't think you'll find many volunteers to do. Unpicking intertwined commits from develop in order to merge them in to master might result in errors going into master immediately before release, after most of the testing has been done. Develop is where everything new comes together and gets tested, any extra process after that is risking breaking it on the way to master.

**Comment by hreintke** [comment]
@raburton : @kireevco 
Lets face reality. We only have a limited number of people who can merge so we can use a process which is led by confidence in keeping the process.
The idea is that we first test the functionality/correctness of a PR BEFORE it is merged into develop.
That means that develop just contains finished PR's. Only issue can be interference between two PR's but that is seen/testes by people using develop branch.
And indeed, if we plan a release, we just wait merging PR's into develop until release is out.

**Comment by raburton** [comment]
@hreintke good, glad we're thinking the same thing, this way makes the most sense!

**Comment by hreintke** [comment]
@raburton : 
On current develop status : Remember I was asking about filtering PR's :smile:
In current develop, not all PR's are tested/agreed. 
I checked all PR's which are currently merged into develop. Some of them are tested and OK now.
The one we are not certain of, I asked the submitters to provide additional information/tests.
In that way I try to get to a develop as stated above -> only containing finished PR's.
New PR's will only go in after proper testing.
That is also why we cannot take a release from develop now. We need some time to clean up.

**Comment by raburton** [comment]
Fair enough. I say go ahead and make this release then. If it's missing a few things it doesn't matter, the next release is planned to follow fairly soon afterwards. For the next release we just need to clean up develop and get any outstanding issues tested then that'll be the next release ready to roll.

**Comment by hreintke** [comment]
@raburton : 
Can you help by merging this PR into master. I think the conflict is the remove of libsming.a from the repo. @piperpilot did also some an update for that.
When done I will create the release based on that.

**Comment by raburton** [comment]
I'll have a go...

**Comment by kireevco** [comment]
Honestly, there are unlimited number of integration issues that can arise, that's why development should never go directly to master.

And Prs should always be tested before merging into develop.

So
How do you make sure that someone won't merge something bad to develop right before you click merge it to master ("release process")? Waiting? Isn't that the thing that everyone was scared about -waiting ? Now the releasing person will be a bottleneck for everyone who just wants to merge new features to develop?


I am Highly against that. We should create a temporary release branch off develop branch, take last minute hotfix patches there of needed and merge it to master, merge changes back to develop, create a release on GitHub and delete that temporary release branch.

Remember, GitHub is different, and all collaboration had to be as asynchronous as possible (while in a normal company you just talk to people, and tell
Them To wait, here this approach will block everything).

**Comment by raburton** [comment]
>How do you make sure that someone won't merge something bad to develop right before you click merge it to master ("release process")?

That's why you have a development freeze. You announce the intention to make a new release and allow a defined time period (a week is reasonable) of freeze, during which time only essential bug fixes go in, nothing new or risky. There are currently only 7 people with the permission to merge something into the develop branch, so they should all know when the development freeze is and not be adding/merging anything new during that time.

>Remember, GitHub is different, and all collaboration had to be as asynchronous as possible (while in a normal company you just talk to people, and tell Them To wait, here this approach will block everything).

This process does not block anything being done because all new work is already happening asynchronously, in forks and pull requests. The actual work isn't supposed to be taking place in develop, it's supposed to be in PRs and only merged when complete and tested. Yes more bugs may crop up with wider testing in develop, that's inevitable and that's why you have a short amount of time when development is stabilised without new things being added for that final bit of testing before the merge.

**Comment by hreintke** [comment]
@kireevco : 
I completely agree with the arguments above from Richard.
One addition : 
> Waiting? Isn't that the thing that everyone was scared about -waiting ? 

The main issue with waiting was the completely uncertain status of all submitted PR's.
There was hardly any feedback and only once in a while some were merged some not for no clear reason.
In the way we are going to work now, PR's, when agreed and ready will go into develop branch -> better feedback, quicker merging into a branch,  and then clear that they will be part of the next release.
The "waiting" that is in here, is just a hold for a short period of time in which no merging to develop will happen. But development on PR's will still continue.

**Comment by kireevco** [comment]
Let's do this and see how it works. 

As for me, I see it as It's the burden of pushing this communication to everyone (now 7 later more people), while with cutting a release branch makes it explicit (and that's why it's been done this way in a standard git-flow). But since @hreintke takes a burden of making sure all 7 people know about freeze - I'm ok.

**Comment by alonewolfx2** [comment]
@kireevco @hreintke @raburton we need to more test about PR's and new features before merge. For ex. Ws2812 library not working correctly. @robotiko realize this. I had same issue and I also fixed.

**Pull request merged**
