### PR TITLE
Custom LWIP compilation: Added full path to the xtensa bin files.

### PR DESCRIPTION
**Pull request by slaff**

### CODE REVIEW

**Comment by anakod** [comment]
How I can apply this fix if I'm already extracted previous Sming version with bug?

**Comment by slaff** [comment]
> How I can apply this fix

Do the following:
```
cd $SMING_HOME
rm -rf third-party/esp-open-lwip
make ENABLE_CUSTOM_LWIP=1
```

**Comment by ADiea** [comment]
Maybe we should define a target cleanthirdparty...

**Comment by slaff** [comment]
> Maybe we should define a target cleanthirdparty...

Take a look at PR #934 .

**Comment by anakod** [comment]
Unfortunately not working for me:

```
C:\DEV\ESP8266\Sming\Sming>make ENABLE_CUSTOM_LWIP=1
Fetching third-party/esp-open-lwip/ ...
Submodule path 'third-party/esp-open-lwip': checked out 'b9a23a6e9ef88d995ae7401
4e71a6a4227f61d62'
c:/DEV/ESP8266/Sming/Sming/third-party/.patches/esp-open-lwip.patch:6: trailing
whitespace.
#ifndef _USER_CONFIG_LWIP_
c:/DEV/ESP8266/Sming/Sming/third-party/.patches/esp-open-lwip.patch:7: trailing
whitespace.
#define _USER_CONFIG_LWIP_
c:/DEV/ESP8266/Sming/Sming/third-party/.patches/esp-open-lwip.patch:8: trailing
whitespace.

c:/DEV/ESP8266/Sming/Sming/third-party/.patches/esp-open-lwip.patch:9: trailing
whitespace.
#ifdef __cplusplus
c:/DEV/ESP8266/Sming/Sming/third-party/.patches/esp-open-lwip.patch:10: trailing
 whitespace.
extern "C" {
Checking patch include/user_config.h...
Checking patch Makefile.open...
error: while searching for:
CC = xtensa-lx106-elf-gcc
AR = xtensa-lx106-elf-ar
DEFS = -DLWIP_OPEN_SRC -DPBUF_RSV_FOR_WLAN -DEBUF_LWIP -DICACHE_FLASH
COPT = -Os
CFLAGS = $(DEFS) $(COPT) -Iinclude -Wl,-EL -mlongcalls -mtext-section-literals $
(CFLAGS_EXTRA)
# Install prefix of esp-open-sdk toolchain
PREFIX = ~/toolchain/xtensa-lx106-elf



error: patch failed: Makefile.open:1
error: Makefile.open: patch does not apply
Checking patch include/arch/cc.h...
error: while searching for:
#include "c_types.h"
#include "ets_sys.h"
#include "osapi.h"
#define EFAULT 14

//#define LWIP_PROVIDE_ERRNO

#if (1)

error: patch failed: include/arch/cc.h:38
error: include/arch/cc.h: patch does not apply
Checking patch include/lwipopts.h...
error: while searching for:
 * an upper limit on the MSS advertised by the remote host.
 */
#ifndef TCP_MSS
#define TCP_MSS                         1460
#endif
#endif


error: patch failed: include/lwipopts.h:953
error: include/lwipopts.h: patch does not apply
make: [third-party/esp-open-lwip/Makefile.open] Error 1 (ignored)
make[1]: Entering directory `/C/DEV/ESP8266/Sming/Sming'
make[2]: Entering directory `/C/DEV/ESP8266/Sming/Sming/third-party/esp-open-lwi
p'
xtensa-lx106-elf-gcc -DLWIP_OPEN_SRC -DPBUF_RSV_FOR_WLAN -DEBUF_LWIP -DICACHE_FL
ASH -Os -Iinclude -Wl,-EL -mlongcalls -mtext-section-literals    -c -o lwip/core
/def.o lwip/core/def.c
make[2]: xtensa-lx106-elf-gcc: Command not found
make[2]: *** [lwip/core/def.o] Error 127
make[2]: Leaving directory `/C/DEV/ESP8266/Sming/Sming/third-party/esp-open-lwip
'
make[1]: *** [compiler/lib/liblwip_open.a] Error 2
make[1]: Leaving directory `/C/DEV/ESP8266/Sming/Sming'
make: *** [third-party/esp-open-lwip/Makefile.open] Error 2
```

**Comment by slaff** [comment]
@anakod Set you git correctly: https://github.com/SmingHub/Sming/wiki/Windows-Quickstart#configure-git-for-windows-environment .

**Comment by anakod** [comment]
Notworked. May be I do something wrong?

```
C:\DEV\ESP8266\Sming\Sming>git config --global core.autocrlf input

C:\DEV\ESP8266\Sming\Sming>make ENABLE_CUSTOM_LWIP=1
Fetching third-party/esp-open-lwip/ ...
Submodule path 'third-party/esp-open-lwip': checked out 'b9a23a6e9ef88d995ae7401
4e71a6a4227f61d62'
c:/DEV/ESP8266/Sming/Sming/third-party/.patches/esp-open-lwip.patch:6: trailing
whitespace.
#ifndef _USER_CONFIG_LWIP_
c:/DEV/ESP8266/Sming/Sming/third-party/.patches/esp-open-lwip.patch:7: trailing
whitespace.
#define _USER_CONFIG_LWIP_
c:/DEV/ESP8266/Sming/Sming/third-party/.patches/esp-open-lwip.patch:8: trailing
whitespace.

c:/DEV/ESP8266/Sming/Sming/third-party/.patches/esp-open-lwip.patch:9: trailing
whitespace.
#ifdef __cplusplus
c:/DEV/ESP8266/Sming/Sming/third-party/.patches/esp-open-lwip.patch:10: trailing
 whitespace.
extern "C" {
Checking patch include/user_config.h...
Checking patch Makefile.open...
error: while searching for:
CC = xtensa-lx106-elf-gcc
AR = xtensa-lx106-elf-ar
DEFS = -DLWIP_OPEN_SRC -DPBUF_RSV_FOR_WLAN -DEBUF_LWIP -DICACHE_FLASH
COPT = -Os
CFLAGS = $(DEFS) $(COPT) -Iinclude -Wl,-EL -mlongcalls -mtext-section-literals $
(CFLAGS_EXTRA)
# Install prefix of esp-open-sdk toolchain
PREFIX = ~/toolchain/xtensa-lx106-elf


error: patch failed: Makefile.open:1
error: Makefile.open: patch does not apply
Checking patch include/arch/cc.h...
error: while searching for:
#include "c_types.h"
#include "ets_sys.h"
#include "osapi.h"
#define EFAULT 14

//#define LWIP_PROVIDE_ERRNO

#if (1)

error: patch failed: include/arch/cc.h:38
error: include/arch/cc.h: patch does not apply
Checking patch include/lwipopts.h...
error: while searching for:
 * an upper limit on the MSS advertised by the remote host.
 */
#ifndef TCP_MSS
#define TCP_MSS                         1460
#endif
#endif


error: patch failed: include/lwipopts.h:953
error: include/lwipopts.h: patch does not apply
make: [third-party/esp-open-lwip/Makefile.open] Error 1 (ignored)
make[1]: Entering directory `/C/DEV/ESP8266/Sming/Sming'
make[2]: Entering directory `/C/DEV/ESP8266/Sming/Sming/third-party/esp-open-lwi
p'
xtensa-lx106-elf-gcc -DLWIP_OPEN_SRC -DPBUF_RSV_FOR_WLAN -DEBUF_LWIP -DICACHE_FL
ASH -Os -Iinclude -Wl,-EL -mlongcalls -mtext-section-literals    -c -o lwip/core
/def.o lwip/core/def.c
make[2]: xtensa-lx106-elf-gcc: Command not found
make[2]: *** [lwip/core/def.o] Error 127
make[2]: Leaving directory `/C/DEV/ESP8266/Sming/Sming/third-party/esp-open-lwip
'
make[1]: *** [compiler/lib/liblwip_open.a] Error 2
make[1]: Leaving directory `/C/DEV/ESP8266/Sming/Sming'
make: *** [third-party/esp-open-lwip/Makefile.open] Error 2
```

**Comment by slaff** [comment]
```
cd C:\DEV\ESP8266\Sming\Sming>
git config --global core.autocrlf input
rm -rf third-party\esp-open-lwip
make ENABLE_CUSTOM_LWIP=1
```

**Comment by anakod** [comment]
@slaff, I understand it of course, I removed folder manually. You can check above log:
```
Fetching third-party/esp-open-lwip/ ...
Submodule path 'third-party/esp-open-lwip': checked out 'b9a23a6e9ef88d995ae7401
4e71a6a4227f61d62'
``

But it still not working :(

**Comment by anakod** [comment]
Probably solution found. I've changed path command line in Sming makefile:
`$(Q) -cd $(dir $@); $(GIT) apply -v $(patsubst third-party/%/,$(SMING_HOME)/third-party/.patches/%.patch, $(dir $@)) --ignore-whitespace`

And than start rebuilding. I'm still have warnings with "trailing whitespace", but looks like everything works fine after that fix.

**Comment by slaff** [comment]
@anakod Can you send PR with the added '--ignore-whitespace' and I will merge it?

**Comment by anakod** [comment]
Ok. I think I've resolved issue with warnings too.

**Comment by anakod** [comment]
Done.

**Comment by ADiea** [comment]
@anakod check wiki for windows installation you should set git line endings to lf only

**Comment by ADiea** [comment]
Ah sorry already pointed out by slaff pls ignore

**Pull request merged**
