### PR TITLE
Smart config 1004

### LINKED ISSUE #1004: smartConfig does not work
The smartConfig sample (and default smartConfig function) does not work. It gets to the SC_STATUS_LINK stage but does not complete.

### PR DESCRIPTION
**Pull request by riban-bw**
Fixes #1004 smartConfig not connecting to WiFi on completion.

### CODE REVIEW

**Comment by slaff** [comment]
There are multiple issues with that PR.
1. There are line ending/spacing changes for files that are not related to this PR. That must be taken care of.
2. I am not sure that the actual change is needed, because I cannot reproduce the issue. At least not with 1.5.* SDK. Is the issue happening with SDK 2.0? Can you elaborate?

**Comment by riban-bw** [comment]
1. I am still struggling with git!!! I will figure out what went wrong and sort that out.
2. I am using SDK 1.5.4 within msys2 environment on Windows 7 and deploying to a NodeMCU (ESP-12) device. (I will add this info to #1004 issue.)

**Comment by slaff** [comment]
@riban-bw Read [CONTRIBUTING.md](https://github.com/SmingHub/Sming/blob/develop/CONTRIBUTING.md) - we have all needed `git` commands there.

**Comment by riban-bw** [comment]
I'm going to close this PR and try again from my fresh fork which doesn't have all those nasty file permission changes.

**Pull request closed without merging**
