### PR TITLE
MEM_USAGE after compilation.

### PR DESCRIPTION
**Pull request by cmarrin**
Added MEM_USAGE perl script and its us to Makefile-project.mk to
give Arduino style ram and flash size output

### CODE REVIEW

**Comment by anakod** [comment]
Is it compatible with Windows?

**Comment by anakod** [comment]
@cmarrin, why you don't like current Sming output with rows in table for RAM and ROM size/usage:

```
#Memory / Section info:
------------------------------------------------------------------------------
   Section|                   Description| Start (hex)|   End (hex)|Used space
------------------------------------------------------------------------------
      data|        Initialized Data (RAM)|    3FFE8000|    3FFE8374|     884
    rodata|           ReadOnly Data (RAM)|    3FFE8378|    3FFEA0B8|    7488
       bss|      Uninitialized Data (RAM)|    3FFEA0B8|    3FFF0F70|   28344 (+8)
      text|            Cached Code (IRAM)|    40100000|    40105D46|   23878
irom0_text|           Uncached Code (SPI)|    40209000|    40244AFA|  244474 (+32)
Total Used RAM : 36716
Free RAM : 45204
Free IRam : 8908
------------------------------------------------------------------------------
```

**Comment by cmarrin** [comment]
> On Nov 3, 2016, at 6:37 AM, Skurydin Alexey <notifications@github.com> wrote:
> 
> @cmarrin <https://github.com/cmarrin>, why you don't like current Sming output with rows in table for RAM and ROM size/usage:
> 
> #Memory / Section info:
> ------------------------------------------------------------------------------
>    Section|                   Description| Start (hex)|   End (hex)|Used space
> ------------------------------------------------------------------------------
>       data|        Initialized Data (RAM)|    3FFE8000|    3FFE8374|     884
>     rodata|           ReadOnly Data (RAM)|    3FFE8378|    3FFEA0B8|    7488
>        bss|      Uninitialized Data (RAM)|    3FFEA0B8|    3FFF0F70|   28344 (+8)
>       text|            Cached Code (IRAM)|    40100000|    40105D46|   23878
> irom0_text|           Uncached Code (SPI)|    40209000|    40244AFA|  244474 (+32)
> Total Used RAM : 36716
> Free RAM : 45204
> Free IRam : 8908
> ———————————————————————————————————————
Hmmm, that looks pretty nice. Is that a new addition? I don’t remember it being there when I added my output.

**Comment by anakod** [comment]
I'm not sure but it already working since some time. May be current implementation isn't same on different OS?

**Comment by kwis2** [comment]
Maybe you would be able to add additional information about sming version?
For instance with MPLABX information after compilation looks like:

> Microchip MPLAB XC8 C Compiler (Free Mode) V1.38
> Build date: Jun 30 2016
> Part Support Version: 1.38
> Copyright (C) 2016 Microchip Technology Inc.
> License type: Node Configuration
> ................
>
> ................
> Memory Summary:
>     Program space        used  1751h (  5969) of  2000h words   ( 72.9%)
>     Data space           used   13Ah (   314) of   400h bytes   ( 30.7%)
>     EEPROM space         None available
>     Data stack space     used     0h (     0) of   2B5h bytes   (  0.0%)
>     Configuration bits   used     2h (     2) of     2h words   (100.0%)
>     ID Location space    used     0h (     0) of     4h bytes   (  0.0%)
>

**Comment by slaff** [comment]
@anakod Under Ubuntu Linux I am getting slighly different information after a sample compilation:
```
C+ app/application.cpp
AR out/build/app_app.a
LD out/build/app.out

#Memory / Section info:
------------------------------------------------------------------------------

out/build/app.out:     file format elf32-xtensa-le

Sections:
Idx Name          Size      VMA       LMA       File off  Algn
  0 .data         00000375  3ffe8000  3ffe8000  000000e0  2**4
                  CONTENTS, ALLOC, LOAD, DATA
  1 .rodata       000003d0  3ffe8380  3ffe8380  00000460  2**4
                  CONTENTS, ALLOC, LOAD, DATA
  2 .bss          000063a8  3ffe8750  3ffe8750  00000830  2**4
                  ALLOC
  3 .irom0.text   0002f558  40209000  40209000  000069b0  2**4
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
  4 .text         00006173  40100000  40100000  00000830  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
------------------------------------------------------------------------------
# Generating image...
Generate firmware images successfully in folder out/firmware.
Done
...
```

Are we using different tools for the different operating systems? I also missing that data
```
Total Used RAM : 36716
Free RAM : 45204
Free IRam : 8908
```
Any ideas where it is lost?

**Comment by kwis2** [comment]
I lost my thread, for sure -  MPLABX  from my post it its quite different enviroment, for diferent processors. 
In my oppinion it is more clear for not advanced user, but the most important - there is information what version of compiler was used.
Idea it was that with a lot of commits I have been loost which Sming I used.

**Pull request closed without merging**
