### PR TITLE
Initial integration of the GDBStub project.

### PR DESCRIPTION
**Pull request by slaff**

### CODE REVIEW

**Comment by kireevco** [comment]
@slaff thank you for a good PR. Can you please re-submit this to _develop_ branch?
right, @hreintke ?

**Comment by hreintke** [comment]
@slaff @kireevco 
Yes please. In that way @slaff will be able to update the PR a keep it up-to-date when necessary.

**Comment by alon24** [comment]
Can you add info on how to use,  does this support Windows?  Mac?  linux?

**Comment by slaff** [comment]
@kireevco What is the right sequence to do this? Shall I do
```
git checkout feature/mqtt
git pull --rebase origin develop
git push my feature/mqtt -f 
```
And use github to submit PR against origin develop or there is an another, easier way to do this?

@alon24
Check the README.md that I have created: https://github.com/slaff/Sming/blob/feature/gdb/Basic_Debug/README.md. In theory you should be able to debug anywhere where you can run the xtensa-gdb debugger.

**Comment by slaff** [comment]
#350 is a cleaner version of this PR against origin develop.

**Pull request closed without merging**
