### PR TITLE
Improve code with `std::unique_ptr`

### PR DESCRIPTION
**Pull request by mikee47**
This PR addresses #2616 using the appropriate C++ mechanisms.
Also some tidying.

### CODE REVIEW

**Comment by mikee47** [comment]
AI seems to like my PR. My life is complete.

**Comment by elfring** [comment]
:crystal_ball: Can my code review comments matter any more here?

**Comment by mikee47** [comment]
> crystal_ball Can my code review comments matter any more here?

Please feel free to comment, I can always open another PR :-)

**Comment by elfring** [comment]
>Please feel free to comment, …

I am still waiting on more constructive feedback for my previous two code review questions on this issue.

**Pull request merged**
