### PR TITLE
Update Contributing to agreed procedure

### PR DESCRIPTION
**Pull request by hreintke**

### CODE REVIEW

**Comment by raburton** [comment]
Can you close, rework or create new pr for updating contribution guidelines, as appropriate.

**Comment by hreintke** [comment]
Sorry, forgot on this one.
Will review but think it is still OK.
If no change needed can we merge this as is ?

**Comment by raburton** [comment]
Yes, if the version in the PR is the right version, but it'll need to be a manual merge.

**Comment by hreintke** [comment]
Just to clarify, I don't want to use shortcuts but understand. 
Is the formal/normal way that I should create a new PR against develop ?

**Comment by raburton** [comment]
For a simple things like this (single file, essentially just a single block of text) the simplest options is probably just to copy out your version of this file, update your development branch to latest, copy the file back in and create a new PR with that changed file against latest develop branch and it will then merge fine. The proper way, if you have a large change set, is to use git to merge as much as possible and resolve the conflicts manually. See the suggested git commands at the bottom of this page for how to do that...

**Comment by raburton** [comment]
In fact even easier way for this one is to go here: https://github.com/SmingHub/Sming/edit/develop/CONTRIBUTING.md copy the contents of the new version in to the editor and commit it directly to the develop branch.

**Comment by hreintke** [comment]
Done the way you proposed

**Comment by raburton** [comment]
Cool, we can close this now then.

**Pull request closed without merging**
