### PR TITLE
Resubmitting HW_PWM . …

### PR DESCRIPTION
**Pull request by hrsavla**
It based on ESP8266 SDK PWM api. It uses hardware timer and does not suffer from flickers. Output on LED will be much better.

### CODE REVIEW

**Comment by kireevco** [comment]
@hrsavla Looks like lots of project files with windows-specific paths, can this be avoided?

**Comment by hreintke** [comment]
@hrsavla : 
We are restructuring and cleaning sming repo and PR's. 
Can you please comment on the question from @kireevco and make sure the HW_PWM is tested by the community. If completed, it will be merged in develop for release within Sming

**Comment by raburton** [comment]
When I try to use hw pwm I get a hang followed by a wdt reset everytime. Your code looks fine, and I've tried a simpler version of just taking enough to call pwm_init and that does the same every time it gets called. Any ideas?

Also, I don't see anywhere in your code above where you add libpwm to the list of libraries, how is that working?

**Comment by raburton** [comment]
@hrsavla any thoughts on this issue? I've played with it quite a bit and still no joy, hangs every time.

**Comment by hreintke** [comment]
@raburton : 
Does the basic_hwpwm example crash at your side ? -> not with me
I did the following : 
- cloned a fresh copy of sminghub/sming, development branch
- fetched PR 264 into local branch hwpwmbranch
- rebased hwpwmbranch on develop
- added pwm to LIBS in makefile-project.mk
- basic_hwpwm runs without crashing
- I cannot see actual hwpwm results as I do not have leds attached.
My environment : 
UDK 2.0.8
Espressif SDK 1.3.0
ESP12e

**Comment by Vity01** [comment]
Any progress on this merge?

**Comment by raburton** [comment]
@hreintke yes it's working now! with the basic sample, I will try it with my own app again and see if there is any improvement, I wonder if it's something to do with the serial port waiting for input in my app???

**Comment by raburton** [comment]
I've reworked this PR, and will submit a new one that can quickly get merged to develop. But I have a question... The current implementation retains a list of the pins, which it then refers to as channels. e.g. channel 1 = pin 13, channel 2 = pin 14, channel 3 = pin 15, then when you want to change a pin you refer to it by channel number and it looks up the pin to operate on. I really can't see any good reason for this, as a developer I'd much rather just use the api by pin number. Any thoughts?

**Comment by alonewolfx2** [comment]
@raburton is right. I think just pin numbers is best way.


2015-10-27 10:00 GMT+02:00 Richard Antony Burton <notifications@github.com>:

> I've reworked this PR, and will submit a new one that can quickly get
> merged to develop. But I have a question... The current implementation
> retains a list of the pins, which it then refers to as channels. e.g.
> channel 1 = pin 13, channel 2 = pin 14, channel 3 = pin 15, then when you
> want to change a pin you refer to it by channel number and it looks up the
> pin to operate on. I really can't see any good reason for this, as a
> developer I'd much rather just use the api by pin number. Any thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SmingHub/Sming/pull/264#issuecomment-151406666>.
>



-- 
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
*[* *Dalından kopan yaprağın akıbetini rüzgar belirler...* *]*
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by raburton** [comment]
Looks like I had that the wrong way around in my head actually, ignore the last question. Anyway, should have this finished off this evening and get a new PR in...

**Comment by raburton** [comment]
please see improved pr #375

**Comment by tprochazka** [comment]
I tihnk that this PR should be closed @raburton PR replaced it.

**Pull request closed without merging**
