### PR TITLE
Fix `pulseIn()`

### PR DESCRIPTION
**Pull request by mikee47**
Very old implementation. Update to use CPU clock as timing reference.

Requires testing with real hardware.

### CODE REVIEW

**Comment by mikee47** [comment]
@SimonBrazell Can you give this PR a try with your sensor, see if it fixes your issues?

**Comment by SimonBrazell** [comment]
@mikee47 will do!

**Comment by slaff** [comment]
@SimonBrazell Any results?

**Comment by SimonBrazell** [comment]
No sorry, I got busy shortly afterwards, I'll see how it goes this evening.

**Comment by SimonBrazell** [comment]
Just tried to build the `Ultrasonic_HCSR04` but `make` failed with the following error:

```
C+ /Users/sbrazell/Developer/Sming/Sming/Core/ArduinoCompat.cpp
In file included from /Users/sbrazell/Developer/Sming/Sming/Core/SmingCore.h:59,
                 from /Users/sbrazell/Developer/Sming/Sming/Core/ArduinoCompat.h:15,
                 from /Users/sbrazell/Developer/Sming/Sming/Core/ArduinoCompat.cpp:13:
/Users/sbrazell/Developer/Sming/Sming/Core/Data/Stream/FileStream.h: In constructor 'FileStream::FileStream(const String&, FileOpenFlags)':
/Users/sbrazell/Developer/Sming/Sming/Core/Data/Stream/FileStream.h:29:92: error: use of deleted function 'FileStream::FileStream() [inherited from IFS::FileStream]'
   29 |  FileStream(const String& fileName, FileOpenFlags openFlags = File::ReadOnly) : FileStream()
      |                                                                                            ^
/Users/sbrazell/Developer/Sming/Sming/Core/Data/Stream/FileStream.h:23:25: note: 'FileStream::FileStream() [inherited from IFS::FileStream]' is implicitly deleted because the default definition would be ill-formed:
   23 |  using IFS::FileStream::FileStream;
      |                         ^~~~~~~~~~
/Users/sbrazell/Developer/Sming/Sming/Core/Data/Stream/FileStream.h:23:25: error: use of deleted function 'IFS::FileStream::FileStream()'
In file included from /Users/sbrazell/Developer/Sming/Sming/Core/Data/Stream/FileStream.h:13,
                 from /Users/sbrazell/Developer/Sming/Sming/Core/SmingCore.h:59,
                 from /Users/sbrazell/Developer/Sming/Sming/Core/ArduinoCompat.h:15,
                 from /Users/sbrazell/Developer/Sming/Sming/Core/ArduinoCompat.cpp:13:
/Users/sbrazell/Developer/Sming/Sming/Core/Data/Stream/IFS/FileStream.h:22:7: note: 'IFS::FileStream::FileStream()' is implicitly deleted because the default definition would be ill-formed:
   22 | class FileStream : public FsBase, public ReadWriteStream
      |       ^~~~~~~~~~
/Users/sbrazell/Developer/Sming/Sming/Core/Data/Stream/IFS/FileStream.h:22:7: error: no matching function for call to 'IFS::FsBase::FsBase()'
In file included from /Users/sbrazell/Developer/Sming/Sming/Components/IFS/src/include/IFS/File.h:22,
                 from /Users/sbrazell/Developer/Sming/Sming/Core/FileSystem.h:19,
                 from /Users/sbrazell/Developer/Sming/Sming/Core/SmingCore.h:22,
                 from /Users/sbrazell/Developer/Sming/Sming/Core/ArduinoCompat.h:15,
                 from /Users/sbrazell/Developer/Sming/Sming/Core/ArduinoCompat.cpp:13:
/Users/sbrazell/Developer/Sming/Sming/Components/IFS/src/include/IFS/FsBase.h:36:2: note: candidate: 'IFS::FsBase::FsBase(IFS::IFileSystem*)'
   36 |  FsBase(IFileSystem* filesys) : fileSystem(FileSystem::cast(filesys))
      |  ^~~~~~
/Users/sbrazell/Developer/Sming/Sming/Components/IFS/src/include/IFS/FsBase.h:36:2: note:   candidate expects 1 argument, 0 provided
/Users/sbrazell/Developer/Sming/Sming/Components/IFS/src/include/IFS/FsBase.h:33:7: note: candidate: 'constexpr IFS::FsBase::FsBase(const IFS::FsBase&)'
   33 | class FsBase
      |       ^~~~~~
/Users/sbrazell/Developer/Sming/Sming/Components/IFS/src/include/IFS/FsBase.h:33:7: note:   candidate expects 1 argument, 0 provided
/Users/sbrazell/Developer/Sming/Sming/Components/IFS/src/include/IFS/FsBase.h:33:7: note: candidate: 'constexpr IFS::FsBase::FsBase(IFS::FsBase&&)'
/Users/sbrazell/Developer/Sming/Sming/Components/IFS/src/include/IFS/FsBase.h:33:7: note:   candidate expects 1 argument, 0 provided
make[2]: *** [Core/ArduinoCompat.o] Error 1
make[1]: *** [Sming-build] Error 2
make: *** [all] Error 2
```

**Comment by mikee47** [comment]
Try `make dist-clean` first.

**Comment by SimonBrazell** [comment]
Okay that did it, it appears to be measuring much more accurately now but with the exception of a few 0 readings in a row from time to time:

Screen Shot 2022-08-06 at 22 01 07

**Comment by slaff** [comment]
> with the exception of a few 0 readings

@mikee47 any idea what might cause the 0 readings?

**Comment by mikee47** [comment]
> > with the exception of a few 0 readings
> 
> @mikee47 any idea what might cause the 0 readings?

50us echo timeout. Disabling interrupts would likely fix that, but more realistically applications should discard 0 reads.

**Comment by slaff** [comment]
> but more realistically applications should discard 0 reads.

Ok, shall I merge the PR as is?

**Comment by mikee47** [comment]
> Ok, shall I merge the PR as is?

Yes, looks like `pulseIn` is doing what it's supposed to.

**Pull request merged**
