### PR TITLE
Adding libwps to Makefile to enable the PBC WPS function

### PR DESCRIPTION
**Pull request by johndoe8967**

### CODE REVIEW

**Comment by slaff** [comment]
@johndoe8967 Isn't it enough for you to add `wps` to `EXTRA_LIBS` in your Makefile-user.mk ?
Do you think that `wps` will be used quite often in projects?

**Comment by johndoe8967** [comment]
@slaff: sure it would be possible, maybe a small template sample would be enough to show the functionality.

**Comment by anakod** [comment]
I think we have example how to add external library, but can't find it now. Anyway it isn't really clear.
@johndoe8967 may be better you can make PR to wiki documentation or PR with example of EXTRA_LIBS usage?

**Comment by slaff** [comment]
Feel free to reopen this PR when the WPS sample is ready.

**Pull request closed without merging**
