### PR TITLE
Update hw profile editor, more like gparted

### PR DESCRIPTION
**Pull request by mikee47**
Show (simplified) map and tree together, and synchronise selection
Implement auto zoom and set ON by default
Enable map scrolling with mousewheel (when autozoom off)
Verify changes (base config, options, editor) before applying and reloading
Use fractional sizes (K, M, G) as appropriate

### CODE REVIEW

**Comment by slaff** [comment]
@mikee47 I am getting python error. I tried the following

```
cd $SMING_HOME/../samples/Basic_Storage/
make SMING_ARCH=Esp8266 hwconfig-edit
```

And got the following error:
```
Basic_Storage: Invoking 'hwconfig-edit' for Esp8266 (debug) architecture
TCL version 8.6
Traceback (most recent call last):
  File "/opt/Sming/Sming/Components/Storage/Tools/hwconfig/editor.py", line 1065, in <module>
    main()
  File "/opt/Sming/Sming/Components/Storage/Tools/hwconfig/editor.py", line 1057, in main
    editor = Editor(root)
  File "/opt/Sming/Sming/Components/Storage/Tools/hwconfig/editor.py", line 770, in __init__
    self.initialise()
  File "/opt/Sming/Sming/Components/Storage/Tools/hwconfig/editor.py", line 830, in initialise
    self.tree = TkTree(pwin, self)
  File "/opt/Sming/Sming/Components/Storage/Tools/hwconfig/editor.py", line 640, in __init__
    self.init()
  File "/opt/Sming/Sming/Components/Storage/Tools/hwconfig/editor.py", line 663, in init
    tree.heading(k, text=v, anchor=tk.W)
  File "/usr/lib/python3.5/tkinter/ttk.py", line 1272, in heading
    return _val_or_dict(self.tk, kw, self._w, 'heading', column)
  File "/usr/lib/python3.5/tkinter/ttk.py", line 297, in _val_or_dict
    res = tk.call(*(args + options))
_tkinter.TclError: Invalid column index size
/opt/Sming/Sming/Components/Storage/component.mk:118: recipe for target 'hwconfig-edit' failed
make: *** [hwconfig-edit] Error 1
```

**Comment by mikee47** [comment]
I think I know why this is happening, but cannot reproduce it. What version of Ubuntu / python3 are you using?

**Comment by slaff** [comment]
> What version of Ubuntu / linux / python3 are you using?

Ubuntu: 16.04 LTS, Python 3.5.2

**Comment by mikee47** [comment]
> 
> 
> > What version of Ubuntu / linux / python3 are you using?
> 
> Ubuntu: 16.04 LTS, Python 3.5.2

Yep, tested with that combination and works without issue. Does the latest commit help?

**Comment by mikee47** [comment]
OK, now it's going pop... even with the fix!

**Comment by slaff** [comment]
Even with the latest commit in this PR I am still getting an error:
 
```
 File "/opt/Sming/Sming/Components/Storage/Tools/hwconfig/editor.py", line 663, in init
    tree.heading(k, text=v, anchor=tk.W)
  File "/usr/lib/python3.5/tkinter/ttk.py", line 1272, in heading
    return _val_or_dict(self.tk, kw, self._w, 'heading', column)
  File "/usr/lib/python3.5/tkinter/ttk.py", line 297, in _val_or_dict
    res = tk.call(*(args + options))
_tkinter.TclError: Invalid column index unused
```

**Comment by mikee47** [comment]
OK, fixed.

**Comment by slaff** [comment]
> OK, fixed.

Confirmed. Looks quite cool :)

**Comment by mikee47** [comment]
@slaff Couple of points to note with old python3 versions:

1. Python 3.5.x is end of life, get this warning when I run `make python-requirements`:

DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.

2. The default `pip` appears to be broken (for python 3.5.2) on ubuntu 16.04. There is a fix e.g. https://askubuntu.com/questions/1317411/pip-version-returns-syntaxerror-invalid-syntax-after-installation.

3. `jsonschema 3.2.0` won't work for python3 < 3.8, so `make hwconfig-validate` will fail. Can downgrade jsonschema with  `python3 -m pip install jsonschema==3.0.2`. See https://stackoverflow.com/questions/59216175/importerror-cannot-import-name-metadata-from-importlib.

**Pull request merged**
