### PR TITLE
New feature: support for adafruit 1.4" TFT display with ST7735 chipset

### PR DESCRIPTION
**Pull request by harry-boe**
includes sample app to demonstrate adafruit GFX lib
includes a demo on how to display a bmp file stored on the spiffy file system

replaces pull request #541 after lots of git cleanup

Feature is tested .. see image as proof
img_1012

### CODE REVIEW

**Comment by alonewolfx2** [comment]
@harry-boe very good. can we adopt this  display a bmp file for ili9341 too?

**Comment by harry-boe** [comment]
@alonewolfx2 should not be a big problem. 

The BPMDraw.h/cpp (in the ST7735 sample project) is basically a straight forward port of the adafruit spitftbitmap.ino sample you find for both adafruit display libraries.

The main difference i that i read from the spiffs file system instead of the SD card to reduce dependencies. 

Porting should be very easy (basically replace the constructor for the display driver) 

Unfortunately a have non of this displays for testing

**Comment by alonewolfx2** [comment]
if you port it i can quick test on ili9341

**Comment by harry-boe** [comment]
I might give it a try tomorrow.

Please note that i have not yet sorted out the HW SPI support.
We struggle here with HW SPI on a port of the ArduCAM project. - That's a Video Camera Module we need for one of our projects.

Question: have you ever tried t get the Display to work with the Sming-Core SPI implementation ?

I know that the ili9341 Lib has it's own hopi driver. I don't know for what reason ?

**Comment by alonewolfx2** [comment]
i ported it on early sming version and i didnt touch again. it didnt work on first version. but maybe it can work on new version.

**Comment by alonewolfx2** [comment]
i think we need arducam project too. but i dont have arducam for porting and testing.

**Comment by harry-boe** [comment]
No worry

We are working on it. Maybe along with some Image conversions and resampling ;)
We do a PR we have something working here. 
It's part of a IoT training session for manager that takes place in march. So it will be tested.

**Comment by alonewolfx2** [comment]
ok i tried ili9341 with sming spi and it seems it can work. its not working yet but i think begin sequence is wrong. if i init screen with old hspi.h and rebuild with sming spi.h its working. soo it will work i think.

**Comment by harry-boe** [comment]
@alonewolfx2  i dit a initial port and made a PR #582 
so it's ready for your tests

**Pull request merged**
