### PR TITLE
moved the implementation of 'getMaxDuty()' into the cpp file for all …

### PR DESCRIPTION
**Pull request by pljakobs**
…architectures. Before, for esp32c3, the function in header would always return 0.

### CODE REVIEW

**Review by mikee47 — COMMENTED** [review]
With #2904 presumably this PR is no longer required?

**Comment by pljakobs** [comment]
this one is about moving the `getMaxDuty()` from the header file into the implementation. 
I don't quite understand why the simple `return maxduty` from the header didn't work for ARCH Esp32 but for Esp8266. It works for both when the function is implemented in the .cpp file. 
#2904 just adds an `assert() ` for max_channels - has nothing to do with this one. I hope I managed to properly untangle the two changes.

**Comment by mikee47** [comment]
> I don't quite understand why the simple `return maxduty` from the header

That's my concern. I can see no logical reason why this PR is necessary so something else is clearly going on.

**Comment by pljakobs** [comment]
I share the concern, but:
I added a `HardwarePWM::myMaxDuty()` function that just did the same thing, `return maxduty`, the only difference was that it was implemented in the .cpp file and only the prototype was in the header.
Calling both functions in the test app one after the other returned `0` for the original `getMaxDuty()` and the correct `1023` from `myGetDuty()`. I could not see any reason for this, but I would be very happy to find one.

**Comment by mikee47** [comment]
I've spun up the `Basic_HwPWM` sample for the esp32c3 to check this. This is what I found:

1. Remove `COMPONENT_SOC` definition from `component.mk` to allow sample to build for other architectures.
2. Add debug statement in `init` to verify `maxDuty`.
3. Flash to esp32c3. This produces a boot-loop:

```
HW PWM maxDuty = 0
E (292) ledc: ledc_set_duty(805): LEDC is not initialized
```

4. The esp32c3 only has *six* PWM channels.  Change `pins` to `LED_PIN, 4, 5, 0,` and application starts OK:

```
HW PWM maxDuty = 1023
PWM output set on all 8 Pins. Kindly check...
Now LED_PIN will go from 0 to VCC to 0 in cycles.
```

**Comment by pljakobs** [comment]
> I've spun up the `Basic_HwPWM` sample for the esp32c3 to check this. This is what I found:
> 
>     1. Remove `COMPONENT_SOC` definition from `component.mk` to allow sample to build for other architectures.
> 
>     2. Add debug statement in `init` to verify `maxDuty`.
> 
>     3. Flash to esp32c3. This produces a boot-loop:
> 
> 
> ```
> HW PWM maxDuty = 0
> E (292) ledc: ledc_set_duty(805): LEDC is not initialized
> ```
> 
>     4. The esp32c3 only has _six_ PWM channels.  Change `pins` to `LED_PIN, 4, 5, 0,` and application starts OK:
> 
> 
> ```
> HW PWM maxDuty = 1023
> PWM output set on all 8 Pins. Kindly check...
> Now LED_PIN will go from 0 to VCC to 0 in cycles.
> ```

are you saying you're getting this result with the `getMaxDuty()` implemented in the .h file? 
I need to re-test this, but I had both issues independently from each other.

**Comment by pljakobs** [comment]
okay, I think I can confirm this. 
I don't quite understand it, though.

**Comment by mikee47** [comment]
Bear in mind that the sample statically initialises the `HardwarePWM` instance, so that happens before the UART has been initialised for debug output.

**Comment by mikee47** [comment]
It's a pity that `HardwarePWM` doesn't follow the usual model where initialisation occurs in a `begin()` method, rather than in the constructor.

**Comment by mikee47** [comment]
> are you saying you're getting this result with the `getMaxDuty()` implemented in the .h file?

Yes. I saw exactly what I expected to see.

**Pull request closed without merging**
