### PR TITLE
[WIP] Panasonic Viera TV remote control

### PR DESCRIPTION
**Pull request by slaff**
A library and sample application that allows you to control a Panasonic Viera TV directly from an embedded device using Sming.

This PR should be merged AFTER #2136.

### CODE REVIEW

**Comment by mikee47** [comment]
@slaff I'm thinking perhaps this and #2136 should be submodules in external repo?

**Comment by slaff** [comment]
> @slaff I'm thinking perhaps this and #2136 should be submodules in external repo?

I agree with you. Would it be possible to review the DIAL PR and this one and if it looks good to you I will put them in separate repo, similar to Sming-UPnP and Sming-SSDP ?

Note to myself -  we are coming close to a recommended file structure for external Sming Libraries. I should spend some time to create a travis.yml template that can be reused in the different external Sming libraries to test / demo the code.

Probably we should also create a `make -C $SMING_HOME sample-app` target in the Sming Library that bootstraps a sample Sming based application and `make -C $SMING_HOME sample-lib` for a Library.

**Comment by mikee47** [comment]
@slaff I've pushed changes to SSDP and UPnP libraries (develop branch) to ensure consistent use of strong enums thoughout. `MessageSpec` is now managed using methods, and you'll need to update types, e.g. `SSDP::TARGET_ROOT` -> `SSDP::SearchTarget::root`.

**Comment by mikee47** [comment]
> 
> 
> > @slaff I'm thinking perhaps this and #2136 should be submodules in external repo?
> 
> I agree with you. Would it be possible to review the DIAL PR and this one and if it looks good to you I will put them in separate repo, similar to Sming-UPnP and Sming-SSDP ?

Will do.

> 
> Note to myself - we are coming close to a recommended file structure for external Sming Libraries. I should spend some time to create a travis.yml template that can be reused in the different external Sming libraries to test / demo the code.

Also I think a template for such an external library with boiler plate stuff like `README.rst`, directory structure, default component.mk, `.gitignore`, `.cs`, etc. I can take care of that one?

> 
> Probably we should also create a `make -C $SMING_HOME sample-app` target in the Sming Library that bootstraps a sample Sming based application and `make -C $SMING_HOME sample-lib` for a Library.

Good idea.  `make fetch` is probably a good starting point?

**Comment by slaff** [comment]
> I can take care of that one? ... make fetch is probably a good starting point

This would be awesome :+1:

**Review by mikee47 — COMMENTED** [review]
@slaff I've done a refactor of this and pushed it to my repo https://github.com/mikee47/Sming/tree/feature/panasonic-tv-remote.

Can't test it but it compiles.

I've changed the Client::Connected callback type from (1) to (2) below.

```
using Connected = Delegate<void(Client& client, HttpConnection& connection, const XML::Document& description)>; // (1)
using Connected = Delegate<void(HttpConnection& connection, const XML::Document& description)>; // (2)
```

I'm leaning towards (2) for a couple of reasons. First, it's simpler, and secondly for the `client` parameter to be useful it may have to be up-cast. In practice it's easier to use a lambda to capture the required parameters instead. In your sample application client is a global so isn't required anyway, which supports my argument in that the application decides how to track it.

Another funny in your code is you've done `(bool)node->getValue()` and `(int)node->getValue()` which doesn't make sense; I've replaced these with calls to `atoi()` assuming they're numeric strings.

**Comment by slaff** [comment]
Once PR #2154 is merged this PR should be reworked and turned into a sample-application-only targeting Panasonic Viera TVs and explaining in more details the different steps needed to
- scan and extract the XML files from your  UPnP device.
- generate code from the XML files.
- use that code to mute the TV, change a channel, get the mute state, etc.

**Pull request closed without merging**
