### PR TITLE
Serial Callback Update

### PR DESCRIPTION
**Pull request by hreintke**
Update Serial Delegate & CommandProcessing

### CODE REVIEW

**Comment by flexiti** [comment]
@hreintke 
eg. void serialCallBack(Stream& stream, char arrivedChar, unsigned short availableCharsCount) 
  from rboot demo  stopped working

**Comment by hreintke** [comment]
@flexiti : 
I should have mentioned the limitations of the patch also in the PR and not only in the issue.

>In there I changed the handling of Serial Delegate & CommandProcessing within the HardwareSerial Class.

>PS : In this patch the availableCharsCount parameter of the delegate does not yet contain the actual count but always is one (1).

The rboot demo uses the availableCharsCount.

**Comment by hreintke** [comment]
I updated the PR to a complete version, supporting all current functionalities of serial delegate & commandprocessing.

Please test and feedback.

**Comment by raburton** [comment]
@hreintke does this need porting to rtos, or is it included / superseded by your rtos serial work?

**Comment by hreintke** [comment]
No, do not merge this one (and any other for HardwareSerial)
HardwareSerial in RTOS has ben rewritten to use freertos specific functions

**Pull request merged**
